### ISSUE TITLE
[BUG] flaky integration test (function.test.js)

### ISSUE THREAD

**Issue by platfowner** [ainblockchain/ain-blockchain#1042]
example run 1:
```
    Function triggering
      Function permission
        Owner only
          ✓ owner only: set_function with ownerOnly = false (_saveLastTx) (4138ms)
          ✓ owner only: set_function with ownerOnly = true (_transfer) (6225ms)
        Rule config with auth.fid
          ✓ write rule with auth.fid: without write value permission (6253ms)
          ✓ write rule with auth.fid: with write value permission (3150ms)
        Rule config with auth.fids
          ✓ write rule with auth.fids: without write value permission (4183ms)
          ✓ write rule with auth.fids: with write value permission (3078ms)
        Owner config with auth.fid
          ✓ owner config with auth.fid: without branch_owner permission (5198ms)
          ✓ owner config with auth.fid: with branch_owner permission (4118ms)
      REST functions whitelist
        ✓ cannot add a function url if not a whitelisted developer (4070ms)
        ✓ cannot whitelist a developer if not an admin (3054ms)
        ✓ can whitelist a developer as an admin (4083ms)
        ✓ can add a function url (4082ms)
        ✓ cannot add an invalid function url (5082ms)
        ✓ cannot add more than the max number of function urls per developer (15311ms)
        ✓ can replace a function url (5094ms)
        ✓ can remove a function url (5110ms)
        ✓ cannot remove other's function urls (4139ms)
      Function execution
        /set_value
          ✓ when successful with function triggering (7242ms)
          ✓ when failed with function triggering (9365ms)
        /set
          ✓ when successful with function triggering (8370ms)
          ✓ when failed with function triggering (9409ms)
      Create app: _createApp
        ✓ when successful with valid app name (3135ms)
        ✓ when failed with null value (5293ms)
        ✓ when failed with invalid app name (6259ms)
        ✓ when failed with invalid admin config (non-boolean value) (7352ms)
        ✓ when failed with invalid admin config (empty) (4130ms)
        ✓ when failed with invalid billing config (non-boolean value) (7269ms)
        ✓ when failed with invalid billing config (missing users) (4151ms)
        ✓ when failed with invalid billing config (non-checksum key) (8342ms)
        ✓ when failed with invalid service config (missing staking config) (4229ms)
        ✓ when failed with invalid service config (invalid staking lockup_duration) (10404ms)
        ✓ when failed with invalid is_public config (4159ms)
        ✓ create a public app (8497ms)
      Gas fee
        ✓ native function (_transfer) with individual account registration (3166ms)
        ✓ native function (_transfer) without individual account registration (3111ms)
        ✓ native function (_transfer) with service account registration (3128ms)
        ✓ native function (_transfer) without service account registration (3145ms)
        ✓ REST function with external RPC call (4174ms)
      Transfer: _transfer
        ✓ transfer: transfer (3109ms)
        ✓ transfer: transfer with null value (5183ms)
        ✓ transfer: transfer more than account balance (6342ms)
        ✓ transfer: transfer by another address (5235ms)
        ✓ transfer: transfer with a duplicated key (4204ms)
        ✓ transfer: transfer with same addresses (3207ms)
        ✓ transfer: transfer with non-checksum addreess (16710ms)
        ✓ transfer: transfer with valid service account service type (4126ms)
        ✓ transfer: transfer with invalid service account service type (3158ms)
        ✓ transfer: transfer with invalid service account service name (4157ms)
      Staking: _stake, _unstake
        Stake:
          ✓ stake: stake (4372ms)
          ✓ stake: stake with null value (4201ms)
          ✓ stake: stake more than account balance (14553ms)
          ✓ stake: stake by another address (7325ms)
          ✓ stake: stake with the same record_id (3169ms)
          ✓ stake: stake with non-checksum addreess (9331ms)
        Unstake:
          ✓ unstake: unstake with null value (5241ms)
          ✓ unstake: unstake by another address (9574ms)
          ✓ unstake: unstake more than staked amount (8490ms)
          ✓ unstake: unstake (4423ms)
          ✓ unstake: stake after unstake (4400ms)
      Payments: _pay, _claim
        ✓ payments: pay by non-app admin (12694ms)
        ✓ payments: pay with amount = 0 (5197ms)
        ✓ payments: pay with amount is not a number (4156ms)
        ✓ payments: pay with payment amount > admin balance (4187ms)
        ✓ payments: pay with null value (7469ms)
        ✓ payments: pay by app admin (4197ms)
        ✓ payments: claim by non-app admin (12517ms)
        ✓ payments: claim with amount > payment balance (7370ms)
        ✓ payments: claim with invalid claim target (8078ms)
        ✓ payments: claim with null value (4704ms)
        ✓ payments: claim by app admin with individual account target (4617ms)
        ✓ payments: claim + hold in escrow by app admin (16043ms)
        ✓ payments: claim by app admin with service account target (8851ms)
      Escrow: _hold, _release
        Escrow: individual -> individual
          ✓ escrow: individual -> individual: open escrow (4164ms)
          ✓ escrow: individual -> individual: cannot open escrow if it's already open (9370ms)
          ✓ escrow: individual -> individual: non-source account cannot write hold (9388ms)
          ✓ escrow: individual -> individual: hold with null value (4186ms)
          ✓ escrow: individual -> individual: source account can write hold (3222ms)
          ✓ escrow: individual -> individual: non-admin account cannot write release (5286ms)
          ✓ escrow: individual -> individual: invalid ratio (ratio = -1) (4139ms)
          ✓ escrow: individual -> individual: invalid ratio (ratio = 1.1) (6197ms)
          ✓ escrow: individual -> individual: release with null value (6334ms)
          ✓ escrow: individual -> individual: admin account can write release (ratio = 0) (5244ms)
        Escrow: service -> individual
          ✓ escrow: service -> individual: open escrow (13604ms)
          ✓ escrow: service -> individual: non-service admin cannot write hold (9322ms)
          ✓ escrow: service -> individual: service admin can write hold (4167ms)
Iteration count exceeded its limit before the given tx 0x69fd706df4a77395058ab3508ed3e52641a9c6d27a3b942d2d7c6e5f88afc08e is finalized!
          1) escrow: service -> individual: admin account can write release (ratio = 0, refund to payments via _transfer)
          2) "after each" hook for "escrow: service -> individual: admin account can write release (ratio = 0, refund to payments via _transfer)"


  85 passing (24m)
  2 failing

  1) Native Function
       Function triggering
         Escrow: _hold, _release
           Escrow: service -> individual
             escrow: service -> individual: admin account can write release (ratio = 0, refund to payments via _transfer):

      AssertionError: expected { …(5) } to deeply equal { func_results: { …(1) }, …(5) }
      + expected - actual

       {
      -  "bandwidth_gas_amount": 0
      -  "code": 10715
      +  "bandwidth_gas_amount": 1
      +  "code": 0
      +  "func_results": {
      +    "_release": {
      +      "bandwidth_gas_amount": 0
      +      "code": 0
      +      "op_results": {
      +        "0": {
      +          "path": "/transfer/escrow|escrow|payments|test_service_escrow|0x01A0980d2D4e418c7F27e1ef539d01A5b5E93204|0:0x00ADEc28B6a845a085e03591bE7550dd68673C1C:1/payments|test_service_escrow|0x01A0980d2D4e418c7F27e1ef539d01A5b5E93204|0/1234567890000/value"
      +          "result": {
      +            "bandwidth_gas_amount": 1
      +            "code": 0
      +            "func_results": {
      +              "_transfer": {
      +                "bandwidth_gas_amount": 0
      +                "code": 0
      +                "op_results": {
      +                  "0": {
      +                    "path": "/service_accounts/escrow/escrow/payments|test_service_escrow|0x01A0980d2D4e418c7F27e1ef539d01A5b5E93204|0:0x00ADEc28B6a845a085e03591bE7550dd68673C1C:1/balance"
      +                    "result": {
      +                      "bandwidth_gas_amount": 1
      +                      "code": 0
      +                    }
      +                  }
      +                  "1": {
      +                    "path": "/service_accounts/payments/test_service_escrow/0x01A0980d2D4e418c7F27e1ef539d01A5b5E93204|0/balance"
      +                    "result": {
      +                      "bandwidth_gas_amount": 1
      +                      "code": 0
      +                    }
      +                  }
      +                }
      +              }
      +            }
      +          }
      +        }
      +      }
      +    }
      +  }
         "gas_amount_charged": "erased"
         "gas_amount_total": {
      +    "bandwidth": {
      +      "service": 4
      +    }
           "state": {
             "service": "erased"
           }
         }
      -  "message": "[executeTransactionAndAddToPool] Tx pool does NOT have enough free room (233)."
      +  "gas_cost_total": 0
       }
      
      at Context.<anonymous> (test/integration/function.test.js:4284:18)
      at processImmediate (node:internal/timers:466:21)

  2) Native Function
       Function triggering
         "after each" hook for "escrow: service -> individual: admin account can write release (ratio = 0, refund to payments via _transfer)":

      AssertionError: expected true to deeply equal false
      + expected - actual

      -true
      +false
      
      at Context.<anonymous> (test/integration/function.test.js:438:14)
      at processImmediate (node:internal/timers:466:21)



```

example run 2:
```
      ...
      Checkout: _openCheckout, _closeCheckout
        ✓ cannot open checkout with invalid params: amount < min_checkout_per_request (8407ms)
        ✓ cannot open checkout with invalid params: amount > max_checkout_per_request (6271ms)
        ✓ cannot open checkout with invalid params: network name (11665ms)
        ✓ cannot open checkout with invalid params: chain id (6241ms)
        ✓ cannot open checkout with invalid params: token id (12436ms)
        ✓ cannot open checkout with invalid params: recipient (8337ms)
        ✓ cannot open checkout with insufficient funds (10404ms)
        ✓ cannot open checkout with null value (9378ms)
        ✓ can open checkout (6269ms)
        ✓ cannot close checkout with a non-authorized address (14600ms)
        ✓ cannot close checkout with null value (6435ms)
        ✓ can close a successful checkout with token pool key (7736ms)
        ✓ can close a failed checkout and refund with token pool key (15753ms)
      Checkin: _openCheckin, _cancelCheckin, _closeCheckin
Iteration count exceeded its limit before the given tx 0xa92621a1f9dcb5d5ab007208c59c8e956d43c6eae26b10ae7c1806121f2e67b4 is finalized!
        ✓ cannot open checkin with invalid params: amount <= 0 (101601ms)
        1) "after each" hook for "cannot open checkin with invalid params: amount <= 0"


  101 passing (43m)
  1 failing

  1) Native Function
       Function triggering
         "after each" hook for "cannot open checkin with invalid params: amount <= 0":

      AssertionError: expected true to deeply equal false
      + expected - actual

      -true
      +false
      
      at Context.<anonymous> (test/integration/function.test.js:438:14)
      at processImmediate (node:internal/timers:466:21)



```

example run3:
```
      Escrow: _hold, _release
        Escrow: individual -> individual
          ✓ escrow: individual -> individual: open escrow (4166ms)
          ✓ escrow: individual -> individual: cannot open escrow if it's already open (4191ms)
          ✓ escrow: individual -> individual: non-source account cannot write hold (4176ms)
          ✓ escrow: individual -> individual: hold with null value (6272ms)
          ✓ escrow: individual -> individual: source account can write hold (4200ms)
          ✓ escrow: individual -> individual: non-admin account cannot write release (4134ms)
          ✓ escrow: individual -> individual: invalid ratio (ratio = -1) (4353ms)
          ✓ escrow: individual -> individual: invalid ratio (ratio = 1.1) (5160ms)
          ✓ escrow: individual -> individual: release with null value (7278ms)
          ✓ escrow: individual -> individual: admin account can write release (ratio = 0) (4371ms)
        Escrow: service -> individual
          ✓ escrow: service -> individual: open escrow (12567ms)
          ✓ escrow: service -> individual: non-service admin cannot write hold (6240ms)
          ✓ escrow: service -> individual: service admin can write hold (4170ms)
          ✓ escrow: service -> individual: admin account can write release (ratio = 0, refund to payments via _transfer) (4229ms)
          ✓ escrow: service -> individual: escrow admin account can write release (ratio = 0.5) (7413ms)
      Checkout: _openCheckout, _closeCheckout
Iteration count exceeded its limit before the given tx 0xa90587cc2c71c7e8f7b6ebdf2abb94e07251478f98ae944ccf7a781a56bda706 is finalized!
Iteration count exceeded its limit before the given tx 0xe120fe733a1a64414b413edc20944ce9d38cdb6407c714e0582973be92396e9e is finalized!
        ✓ cannot open checkout with invalid params: amount < min_checkout_per_request (157269ms)
        1) cannot open checkout with invalid params: amount < min_checkout_per_request
        2) "after each" hook for "cannot open checkout with invalid params: amount < min_checkout_per_request"


  88 passing (26m)
  2 failing

  1) Native Function
       Function triggering
         Checkout: _openCheckout, _closeCheckout
           cannot open checkout with invalid params: amount < min_checkout_per_request:
     Uncaught Error: write EPIPE
      at afterWriteDispatched (node:internal/stream_base_commons:160:15)
      at writeGeneric (node:internal/stream_base_commons:151:3)
      at Socket._writeGeneric (node:net:795:11)
      at Socket._write (node:net:807:8)
      at writeOrBuffer (node:internal/streams/writable:389:12)
      at _write (node:internal/streams/writable:330:10)
      at Socket.Writable.write (node:internal/streams/writable:334:10)
      at console.value (node:internal/console/constructor:286:16)
      at console.warn (node:internal/console/constructor:365:26)
      at Context.<anonymous> (test/integration/function.test.js:4440:19)

  2) Native Function
       Function triggering
         "after each" hook for "cannot open checkout with invalid params: amount < min_checkout_per_request":

      AssertionError: expected true to deeply equal false
      + expected - actual

      -true
      +false
      
      at Context.<anonymous> (test/integration/function.test.js:437:14)
      at processImmediate (node:internal/timers:466:21)



```

**Comment by platfowner** [comment]
Fixed:
- "Uncaught Error: write EPIPE" error was fixed by #1043 
- "Iteration count exceeded" error was fixed by machine reset
