### ISSUE TITLE
[BUG] [loadAndExecuteChainOnDb] Failed to load block 781757

### ISSUE THREAD

**Issue by platfowner** [ainblockchain/ain-blockchain#1083]
While deploying (see https://github.com/ainblockchain/ain-blockchain/issues/1080), failed to load block.

node-8080-error-12-Jul-22.log:
```
{"name":"mainnet-prod","hostname":"mainnet-node-9-netherlands","pid":5507,"level":50,"msg":"[FILE-UTIL] [readCompressedJsonSync] Error while reading /home/ain_blockchain_data/chains/8080/n2b/7/781757.json.gz: Error: unexpected end of file","time":"2022-07-12T08:08:54.193Z","v":0}
{"name":"mainnet-prod","hostname":"mainnet-node-9-netherlands","pid":5507,"level":50,"msg":"[FILE-UTIL] [readCompressedJsonSync] Error while reading /home/ain_blockchain_data/chains/8080/n2b/7/781757.json.gz: Error: unexpected end of file","time":"2022-07-12T08:08:54.221Z","v":0}
{"name":"mainnet-prod","hostname":"mainnet-node-9-netherlands","pid":5507,"level":50,"msg":"[NODE] [loadAndExecuteChainOnDb] Failed to load block 781757.\nError\n    at Function.logErrorWithStackTrace (/home/ain-blockchain-2022-07-12T08-01/common/common-util.js:823:33)\n    at Function.finishWithStackTrace (/home/ain-blockchain-2022-07-12T08-01/common/common-util.js:833:16)\n    at BlockchainNode.loadAndExecuteChainOnDb (/home/ain-blockchain-2022-07-12T08-01/node/index.js:834:20)\n    at BlockchainNode.startNode (/home/ain-blockchain-2022-07-12T08-01/node/index.js:377:17)\n    at P2pClient.startBlockchainNode (/home/ain-blockchain-2022-07-12T08-01/p2p/index.js:526:27)\n    at P2pClient.prepareBlockchainNode (/home/ain-blockchain-2022-07-12T08-01/p2p/index.js:513:16)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async P2pClient.run (/home/ain-blockchain-2022-07-12T08-01/p2p/index.js:72:7).","time":"2022-07-12T08:08:54.221Z","v":0}
{"name":"mainnet-prod","hostname":"mainnet-node-9-netherlands","pid":8690,"level":50,"msg":"[FILE-UTIL] [readCompressedJsonSync] Error while reading /home/ain_blockchain_data/chains/8080/n2b/7/781757.json.gz: Error: unexpected end of file","time":"2022-07-12T08:44:14.431Z","v":0}
{"name":"mainnet-prod","hostname":"mainnet-node-9-netherlands","pid":8690,"level":50,"msg":"[FILE-UTIL] [readCompressedJsonSync] Error while reading /home/ain_blockchain_data/chains/8080/n2b/7/781757.json.gz: Error: unexpected end of file","time":"2022-07-12T08:44:14.462Z","v":0}
{"name":"mainnet-prod","hostname":"mainnet-node-9-netherlands","pid":8690,"level":50,"msg":"[NODE] [loadAndExecuteChainOnDb] Failed to load block 781757.\nError\n    at Function.logErrorWithStackTrace (/home/ain-blockchain-2022-07-12T08-37/common/common-util.js:823:33)\n    at Function.finishWithStackTrace (/home/ain-blockchain-2022-07-12T08-37/common/common-util.js:833:16)\n    at BlockchainNode.loadAndExecuteChainOnDb (/home/ain-blockchain-2022-07-12T08-37/node/index.js:834:20)\n    at BlockchainNode.startNode (/home/ain-blockchain-2022-07-12T08-37/node/index.js:377:17)\n    at P2pClient.startBlockchainNode (/home/ain-blockchain-2022-07-12T08-37/p2p/index.js:526:27)\n    at P2pClient.prepareBlockchainNode (/home/ain-blockchain-2022-07-12T08-37/p2p/index.js:513:16)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async P2pClient.run (/home/ain-blockchain-2022-07-12T08-37/p2p/index.js:72:7).","time":"2022-07-12T08:44:14.463Z","v":0}
```

**Comment by platfowner** [comment]
Turned out that block 781757 is empty:
![781757](https://user-images.githubusercontent.com/46211617/178455789-acf03ad3-4da1-4ed6-ac12-c0afc614a885.jpg)

**Comment by platfowner** [comment]
Retried after deleting the file:
```
{"name":"mainnet-prod","hostname":"mainnet-node-9-netherlands","pid":10450,"level":50,"msg":"[BLOCKCHAIN] [writeBlock] Overwriting h2n file for block 781755 of hash 0xbe46d9068fefb2fa380be599bb856accd26b181e89b9742fe4ae0e2912d2c338","time":"2022-07-12T09:06:12.065Z","v":0}
{"name":"mainnet-prod","hostname":"mainnet-node-9-netherlands","pid":10450,"level":50,"msg":"[BLOCKCHAIN] [writeBlock] Overwriting h2n file for block 781756 of hash 0x7228248acf9a9c096f53dbb7a110e39bdca0ce4ca44a857422027dee52fb7c45","time":"2022-07-12T09:06:12.106Z","v":0}
{"name":"mainnet-prod","hostname":"mainnet-node-9-netherlands","pid":10450,"level":50,"msg":"[BLOCKCHAIN] [writeBlock] Overwriting h2n file for block 781757 of hash 0x389acf6a590f4995a53c70b895f521103d8a635e04f342d13dca87aeaa44f6b8","time":"2022-07-12T09:06:12.146Z","v":0}
...
{"name":"mainnet-prod","hostname":"mainnet-node-9-netherlands","pid":10450,"level":50,"msg":"[CONSENSUS] No previous block of number 829688 and hash 0xa7880b01a1eca54d408536c3bc2db479cf484ff26cde53e2821fb034fb1b3a93","time":"2022-07-12T09:31:16.518Z","v":0}
{"name":"mainnet-prod","hostname":"mainnet-node-9-netherlands","pid":10450,"level":50,"msg":"[CONSENSUS] No previous block of number 829687 and hash 0x6b661bf1529509235299e67f2441a5bbc39bc7a760a10e968fac07e8d8de8e67","time":"2022-07-12T09:31:17.441Z","v":0}
{"name":"mainnet-prod","hostname":"mainnet-node-9-netherlands","pid":10450,"level":50,"msg":"[CONSENSUS] No previous block of number 829688 and hash 0xa7880b01a1eca54d408536c3bc2db479cf484ff26cde53e2821fb034fb1b3a93","time":"2022-07-12T09:31:17.442Z","v":0}
```

**Comment by platfowner** [comment]
Duplicates https://github.com/ainblockchain/ain-blockchain/issues/1061
