### ISSUE TITLE
[ALERT] 2022-10-06 blockchain unstable

### ISSUE THREAD

**Issue by platfowner** [ainblockchain/ain-blockchain#1103]
blockchain is unstable: 

![num_nodes_alive_before](https://user-images.githubusercontent.com/46211617/194168608-d49eb857-0024-4bf9-87f5-6fc93fdddd6d.jpg)

![number_before](https://user-images.githubusercontent.com/46211617/194168623-e4d6a65d-765d-40d9-af8d-64c5d83429ae.jpg)

![topology_before](https://user-images.githubusercontent.com/46211617/194168638-3010b75b-5b78-4110-8a24-5a74c1085485.jpg)

**Comment by platfowner** [comment]
node 0 is unstable but the job is alive:
![job_before](https://user-images.githubusercontent.com/46211617/194168863-7b2197b1-d2cf-4514-a655-35be6c3b3f12.jpg)

logs:
```
{"name":"mainnet-prod","hostname":"mainnet-node-0-taiwan","pid":13795,"level":50,"msg":"[CONSENSUS] ntpsync error: Error: Operation timed out Error: Operation timed out\n    at throwTimeoutErrorFunc (/home/ain-blockchain-2022-09-26T14-06/node_modules/ntpsync/distribution/ntpBurstRequest.js:131:15)","time":"2022-10-05T13:50:28.492Z","v":0}
...
{"name":"mainnet-prod","hostname":"mainnet-node-0-taiwan","pid":13795,"level":50,"msg":"[RADIX_TREE] [get] A node without state node with label: 4\nError\n    at Function.logErrorWithStackTrace (/home/ain-blockchain-2022-09-26T14-06/common/common-util.js:823:33)\n    at RadixTree.get (/home/ain-blockchain-2022-09-26T14-06/db/radix-tree.js:209:18)\n    at StateNode.getChild (/home/ain-blockchain-2022-09-26T14-06/db/state-node.js:330:34)\n    at Function.getRefForReadingFromStateRoot (/home/ain-blockchain-2022-09-26T14-06/db/index.js:395:26)\n    at DB.getRefForReading (/home/ain-blockchain-2022-09-26T14-06/db/index.js:406:15)\n    at DB.getStateInfo (/home/ain-blockchain-2022-09-26T14-06/db/index.js:598:28)\n    at DB.getStateUsageAtPath (/home/ain-blockchain-2022-09-26T14-06/db/index.js:1603:12)\n    at DB.updateAppStateUsageCache (/home/ain-blockchain-2022-09-26T14-06/db/index.js:1530:34)\n    at DB.updateStateFreeTierUsageCache (/home/ain-blockchain-2022-09-26T14-06/db/index.js:1565:38)\n    at new DB (/home/ain-blockchain-2022-09-26T14-06/db/index.js:76:10).","time":"2022-10-05T13:50:44.486Z","v":0}
```

**Comment by platfowner** [comment]
restart node job:
```
bash deploy_blockchain_incremental_gcp.sh mainnet runner 0 0 0 --keystore --keep-code --keep-data --no-chown-data
```

**Comment by platfowner** [comment]
blockchain is stablized:

![num_nodes_alive_after](https://user-images.githubusercontent.com/46211617/194169240-8349ce3e-6bae-478c-9375-a68925b05806.jpg)

![number_after](https://user-images.githubusercontent.com/46211617/194169278-2faaf0a3-9f5b-4de0-b9d6-531651a562cc.jpg)

![topology_after](https://user-images.githubusercontent.com/46211617/194169298-643d8461-7dd0-45ab-b63f-bf1ad183ec57.jpg)
