### ISSUE TITLE
[BUG] mainnet alerting 2023-01-29

### ISSUE THREAD

**Issue by platfowner** [ainblockchain/ain-blockchain#1135]
![num_nodes_alive](https://user-images.githubusercontent.com/46211617/215310515-d7685e99-e26c-4daf-914a-9e6d2a3d4556.jpg)

![block_status_number_node0](https://user-images.githubusercontent.com/46211617/215310518-06a00b20-1e4f-421d-ae30-e0a9268656b5.jpg)

**Comment by platfowner** [comment]
node-8080-error-29-Jan-23.log:
```
{"name":"mainnet-prod","hostname":"mainnet-node-0-taiwan","pid":15943,"level":50,"msg":"[RADIX_TREE] [get] A node without state node with label: 4\nError\n    at Function.logErrorWithStackTrace (/home/ain-blockchain-2023-01-26T04-59/common/common-util.js:823:33)\n    at RadixTree.get (/home/ain-blockchain-2023-01-26T04-59/db/radix-tree.js:209:18)\n    at StateNode.getChild (/home/ain-blockchain-2023-01-26T04-59/db/state-node.js:330:34)\n    at Function.getRefForReadingFromStateRoot (/home/ain-blockchain-2023-01-26T04-59/db/index.js:395:26)\n    at DB.getRefForReading (/home/ain-blockchain-2023-01-26T04-59/db/index.js:406:15)\n    at DB.getStateInfo (/home/ain-blockchain-2023-01-26T04-59/db/index.js:598:28)\n    at DB.getStateUsageAtPath (/home/ain-blockchain-2023-01-26T04-59/db/index.js:1603:12)\n    at DB.updateAppStateUsageCache (/home/ain-blockchain-2023-01-26T04-59/db/index.js:1530:34)\n    at DB.updateStateFreeTierUsageCache (/home/ain-blockchain-2023-01-26T04-59/db/index.js:1565:38)\n    at new DB (/home/ain-blockchain-2023-01-26T04-59/db/index.js:76:10).","time":"2023-01-29T05:57:32.412Z","v":0}
```

**Comment by platfowner** [comment]
Restart node 0:
```
bash deploy_blockchain_incremental_gcp.sh mainnet 0 0 0 --keystore --keep-code --keep-data
```

**Comment by platfowner** [comment]
![num_nodes_alive2](https://user-images.githubusercontent.com/46211617/215311169-2ef493f8-0f5a-47a9-9054-54279d27214d.jpg)

![block_status_number_node0_2](https://user-images.githubusercontent.com/46211617/215311174-414433f5-8296-4a6a-b8cc-bd003319a7d1.jpg)

**Comment by platfowner** [comment]
Issue closed.
