### ISSUE TITLE
[BUG] Block is not extending one of the longest notarized chains

### ISSUE THREAD

**Issue by platfowner** [ainblockchain/ain-blockchain#160]
I don't know why yet but it was not detected while developing and testing new features for a while since `yarn run test_unit` tells nothing about this. I shows the error messages of the failure only with individual test run command:
```
./node_modules/mocha/bin/mocha --timeout 160000 unittest/block-pool.test.js
```

@liayoo , could you take a look (seems not very critical? not sure). I had a quick look but due to the complexity of the code, it wasn't easy to catch something.

```
  2 passing (569ms)
  2 failing

  1) BlockPool
       Returns a finalizable chain:
     AssertionError: expected undefined to equal true
      at Context.it (unittest/block-pool.test.js:128:65)

  2) BlockPool
       Correctly returns the longest notarized chain:

      AssertionError: expected [ Array(1) ] to deeply equal [ Array(1) ]
      + expected - actual

               "0x03AAb7b6f16A92A1dfe018Fe34ee420eb098B98A": 250
               "0x04A456C92A880cd59D7145C457475515a6f6E0f2": 250
             }
           }
      +    {
      +      "epoch": 1
      +      "hash": "0x8997cc89f6e696e2a11fe4801c6908bf7572eb505f803309da2b75b8d3d89795"
      +      "last_hash": "0xdc5e82aca85f691dbe43403379b79c167d9d9acfd62349e69cb8621497868ac4"
      +      "last_votes": []
      +      "last_votes_hash": "0x853fb99c831d4952ff90b897bd7d7c5c2f3747e8eda8ad13e7359b731eadc299"
      +      "number": 1
      +      "proposer": "0x00ADEc28B6a845a085e03591bE7550dd68673C1C"
      +      "size": 0
      +      "stateProofHash": ""
      +      "timestamp": 1607917657536
      +      "transactions": []
      +      "transactions_hash": "0x853fb99c831d4952ff90b897bd7d7c5c2f3747e8eda8ad13e7359b731eadc299"
      +      "validators": {
      +        "0x00ADEc28B6a845a085e03591bE7550dd68673C1C": 250
      +      }
      +    }
      +    {
      +      "epoch": 3
      +      "hash": "0x0b2b8a375d804a60db36f6aff9f6f3c2a3f490d70337e879eb6757bce2aef0a9"
      +      "last_hash": "0x8997cc89f6e696e2a11fe4801c6908bf7572eb505f803309da2b75b8d3d89795"
      +      "last_votes": []
      +      "last_votes_hash": "0x853fb99c831d4952ff90b897bd7d7c5c2f3747e8eda8ad13e7359b731eadc299"
      +      "number": 2
      +      "proposer": "0x00ADEc28B6a845a085e03591bE7550dd68673C1C"
      +      "size": 0
      +      "stateProofHash": ""
      +      "timestamp": 1607917657539
      +      "transactions": []
      +      "transactions_hash": "0x853fb99c831d4952ff90b897bd7d7c5c2f3747e8eda8ad13e7359b731eadc299"
      +      "validators": {
      +        "0x00ADEc28B6a845a085e03591bE7550dd68673C1C": 250
      +      }
      +    }
      +    {
      +      "epoch": 5
      +      "hash": "0xc9fca3f85199e3434443caaef0f70cf7b03fbb7599acf3520eadd22c99f2a016"
      +      "last_hash": "0x0b2b8a375d804a60db36f6aff9f6f3c2a3f490d70337e879eb6757bce2aef0a9"
      +      "last_votes": []
      +      "last_votes_hash": "0x853fb99c831d4952ff90b897bd7d7c5c2f3747e8eda8ad13e7359b731eadc299"
      +      "number": 3
      +      "proposer": "0x00ADEc28B6a845a085e03591bE7550dd68673C1C"
      +      "size": 0
      +      "stateProofHash": ""
      +      "timestamp": 1607917657545
      +      "transactions": []
      +      "transactions_hash": "0x853fb99c831d4952ff90b897bd7d7c5c2f3747e8eda8ad13e7359b731eadc299"
      +      "validators": {
      +        "0x00ADEc28B6a845a085e03591bE7550dd68673C1C": 250
      +      }
      +    }
      +    {
      +      "epoch": 7
      +      "hash": "0xd8fee754ee96cc3e06373db532a0a35e75941c3df2f0dd06eb85111eb5dbb024"
      +      "last_hash": "0xc9fca3f85199e3434443caaef0f70cf7b03fbb7599acf3520eadd22c99f2a016"
      +      "last_votes": []
      +      "last_votes_hash": "0x853fb99c831d4952ff90b897bd7d7c5c2f3747e8eda8ad13e7359b731eadc299"
      +      "number": 4
      +      "proposer": "0x00ADEc28B6a845a085e03591bE7550dd68673C1C"
      +      "size": 0
      +      "stateProofHash": ""
      +      "timestamp": 1607917657550
      +      "transactions": []
      +      "transactions_hash": "0x853fb99c831d4952ff90b897bd7d7c5c2f3747e8eda8ad13e7359b731eadc299"
      +      "validators": {
      +        "0x00ADEc28B6a845a085e03591bE7550dd68673C1C": 250
      +      }
      +    }
         ]
       ]
      
      at Context.it (unittest/block-pool.test.js:203:12)

```

**Comment by platfowner** [comment]
Could this be related with the following error messages from the field testing servers in dev / prod-spring?
```
{
  "insertId": ".......B_tSIYFzyUixC0sIVjVb_g9XK",
  "jsonPayload": {
    "metadata": {},
    "message": "[CONSENSUS] [checkProposal] Block is not extending one of the longest notarized chains ([\n  \"0x1512217b4abad016069f546040b3c9e3cad7d4e561f89edf293449f73fc0af2f\"\n])"
  },
  "resource": {
    "type": "gce_instance",
    "labels": {
      "project_id": "testnet-dev-ground",
      "instance_id": "4460521773284006620",
      "zone": "asia-east1-b"
    }
  },
  "timestamp": "2020-12-14T01:14:45.282000064Z",
  "severity": "ERROR",
  "logName": "projects/testnet-dev-ground/logs/winston_log",
  "receiveTimestamp": "2020-12-14T01:14:45.335808485Z"
}
```

Interestingly, the servers on staging with enableStateVersionOpt=false don't give this kind of error messages at all. @liayoo

**Comment by liayoo** [comment]
Ah, I figured it out! You need NUM_VALIDATORS=1 for the test to work. It's included in the `test_unit` npm script, but would need to include manually if someone wants to run a single test. I'll add a single test script for the block pool in package.json for now, and try to think of a better way to deal with this..

**Comment by platfowner** [comment]
The test was fixed by #161. The error messages are under investigation.

**Comment by platfowner** [comment]
Changing issue title: "Some test cases in unittest/block-pool.test.js fails" -> "Block is not extending one of the longest notarized chains"

**Comment by platfowner** [comment]
@liayoo

**Comment by platfowner** [comment]
Discussed offline: It's not very normal but something that can happen some network circumstances. So we can just keep it as errors.
