### ISSUE TITLE
[BUG] State version bloats

### ISSUE THREAD

**Issue by platfowner** [ainblockchain/ain-blockchain#175]
**Describe the bug**
State version bloats.
/state_versions:
```
{
    "code": 0,
    "result": {
        "version_list": [
            "EMPTY",
            "TEMP:1609604075169:1121",
            "TEMP:1609604081165:2090",
            "TEMP:1609604144192:6026",
...
            "TEMP:1609650339098:6071",
            "TEMP:1609650362842:5856",
            "TEMP:1609665815887:8530",
            "TEMP:1609665818725:795",
            "FINAL:16409",
            "NODE:16409"
        ],
        "final_version": "FINAL:16409"
    }
}
```

**To Reproduce**
1. Add the following debugging code to state manager:
```
  cloneVersion(version, newVersion) {
    if (this.numVersions() > 11) {
      console.log(`!!!!!!!!!!!!!!!!!!!!!getVersionList(): ${JSON.stringify(this.getVersionList(), null, 2)}`);
      console.trace();
      process.exit(1);
    }
```
2. Run blockchain locally with at least 2 nodes (Tip: giving shorter value to EPOCH_MS (e.g. 200) can make the reproduction faster) 

**Expected behavior**

**System information:**
 - OS & version: [e.g. Windows/Linux/OSX]
 - ain-util version: [e.g. 1.1.6]
 - Commit hash: [e.g. 8cf3db6]

**Screenshots**

**Additional context**

**Comment by platfowner** [comment]
We some debugging code:
```
!!!getVersionList(): [
  "EMPTY",
  "POOL:438:1609731322057:0",
  "POOL:439:1609731322258:0",
  "FINAL:440",
  "NODE:440",
  "POOL:440:1609731322665:0",
  "POOL:440:1609731322680:0",
  "POOL:440:1609731322884:0",
  "POOL:440:1609731323290:0",
  "POOL:440:1609731323479:0",
  "POOL:440:1609731323685:0",
  "POOL:440:1609731324087:0"
]
Trace
    at StateManager.cloneVersion (/Users/seo/git/comcomai/blockchain/ain-blockchain/db/state-manager.js:122:11)
    at BlockchainNode.createDb (/Users/seo/git/comcomai/blockchain/ain-blockchain/node/index.js:93:39)
    at BlockchainNode.createTempDb (/Users/seo/git/comcomai/blockchain/ain-blockchain/node/index.js:88:17)
    at Consensus.getSnapDb (/Users/seo/git/comcomai/blockchain/ain-blockchain/consensus/index.js:821:30)
    at Consensus.checkVoteTx (/Users/seo/git/comcomai/blockchain/ain-blockchain/consensus/index.js:604:25)
    at Consensus.handleConsensusMessage (/Users/seo/git/comcomai/blockchain/ain-blockchain/consensus/index.js:245:59)
    at Consensus.vote (/Users/seo/git/comcomai/blockchain/ain-blockchain/consensus/index.js:690:10)
    at Consensus.tryVote (/Users/seo/git/comcomai/blockchain/ain-blockchain/consensus/index.js:663:10)
    at Consensus.handleConsensusMessage (/Users/seo/git/comcomai/blockchain/ain-blockchain/consensus/index.js:238:14)
    at Consensus.tryPropose (/Users/seo/git/comcomai/blockchain/ain-blockchain/consensus/index.js:640:16)
```

**Comment by platfowner** [comment]
Not reproducible with release/R31 branch: https://github.com/ainblockchain/ain-blockchain/tree/release/R31
