### ISSUE TITLE
[BUG] prod summer tracker server died 

### ISSUE THREAD

**Issue by platfowner** [ainblockchain/ain-blockchain#247]
prod summer tracker server died with the following error message:
```
(node:25813) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:25813) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:25813) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:25813) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:25813) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:25813) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
/home/ain-blockchain/node_modules/winston/lib/winston/logger.js:307
      throw ex;
      ^

Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:399:19)
    at writeOrBuffer (_stream_writable.js:387:5)
    at WriteStream.Writable.write (_stream_writable.js:318:11)
    at Object.<anonymous> (/home/ain-blockchain/node_modules/file-stream-rotator/FileStreamRotator.js:616:26)
    at DailyRotateFile.log (/home/ain-blockchain/node_modules/winston-daily-rotate-file/daily-rotate-file.js:157:20)
    at DailyRotateFile._write (/home/ain-blockchain/node_modules/winston-transport/index.js:103:17)
    at doWrite (/home/ain-blockchain/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/home/ain-blockchain/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at DailyRotateFile.Writable.write (/home/ain-blockchain/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at DerivedLogger.ondata (/home/ain-blockchain/node_modules/readable-stream/lib/_stream_readable.js:681:20)
Emitted 'error' event at:
    at WriteStream.<anonymous> (/home/ain-blockchain/node_modules/file-stream-rotator/FileStreamRotator.js:677:15)
    at WriteStream.emit (events.js:314:20)
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at onwriteError (_stream_writable.js:418:5)
    at onwrite (_stream_writable.js:445:5)
    at doWrite (_stream_writable.js:399:11)
    at writeOrBuffer (_stream_writable.js:387:5)
    [... lines matching original stack trace ...]
    at DailyRotateFile.log (/home/ain-blockchain/node_modules/winston-daily-rotate-file/daily-rotate-file.js:157:20) {
  code: 'ERR_STREAM_DESTROYED'
}
```

**Comment by platfowner** [comment]
It turned out that the instance exhausted disk space:
```
df -h

No zone specified. Using zone [asia-east1-b] for instance: [summer-tracker-taiwan].
Filesystem      Size  Used Avail Use% Mounted on
udev            1.8G     0  1.8G   0% /dev
tmpfs           369M   38M  331M  11% /run
/dev/sda1        20G   20G     0 100% /
tmpfs           1.8G     0  1.8G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           1.8G     0  1.8G   0% /sys/fs/cgroup
/dev/loop3       56M   56M     0 100% /snap/core18/1944
/dev/loop4       98M   98M     0 100% /snap/core/10583
/dev/sda15      105M  3.6M  101M   4% /boot/efi
/dev/loop6       56M   56M     0 100% /snap/core18/1988
/dev/loop5       99M   99M     0 100% /snap/core/10823
/dev/loop1      153M  153M     0 100% /snap/google-cloud-sdk/169
/dev/loop2      153M  153M     0 100% /snap/google-cloud-sdk/170
tmpfs           369M     0  369M   0% /run/user/1001
```

So we need to optimize winston log messages:
```
du -s du -s /home/ain-blockchain/logger/logs/808

No zone specified. Using zone [asia-east1-b] for instance: [summer-tracker-taiwan].
13411324	/home/ain-blockchain/logger/logs/8080
```

**Comment by platfowner** [comment]
Just cleaned up the log files and patched the fix code: https://github.com/ainblockchain/ain-blockchain/pull/248 

And restarted the tracker server.

**Comment by platfowner** [comment]
@minsulee2 Just re-opened. Feel free to close it once your investigation finishes.
