### ISSUE TITLE
[BUG] Broken sharding test

### ISSUE THREAD

**Issue by liayoo** [ainblockchain/ain-blockchain#336]
**Describe the bug**
Sharding test is broken since #329.

2021-04-16T15:17:25.157Z [node-0-9091] error: [SERVER_UTIL] Failed to send transaction: Error: Request failed with status code 500
2021-04-16T15:17:25.158Z [node-0-9091] error: [P2P_SERVER] Error: Failed to sign and send tx: Request failed with status code 500
    at sendTxAndWaitForFinalization (/Users/liayoo/comcom/ain-blockchain/p2p/util.js:19:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async P2pServer.setUpDbForSharding (/Users/liayoo/comcom/ain-blockchain/p2p/server.js:603:5)
    at async P2pServer.tryInitializeShard (/Users/liayoo/comcom/ain-blockchain/p2p/server.js:593:7)
    at async WebSocket.<anonymous> (/Users/liayoo/comcom/ain-blockchain/p2p/index.js:169:13)

**To Reproduce**
1. Run ./node_modules/mocha/bin/mocha --timeout 320000 integration/sharding.test.js
2. See error in logs/node-0-9091-error-*.log

**Comment by liayoo** [comment]
+Other integration tests also broken (blockchain and node)

**Comment by platfowner** [comment]
It seems the issue begins from https://github.com/ainblockchain/ain-blockchain/pull/329/files
@minsulee2 , could you take a look?
