### ISSUE TITLE
[BUG] Integration test breaks 

### ISSUE THREAD

**Issue by platfowner** [ainblockchain/ain-blockchain#340]
- How to reproduce:
  - `./node_modules/mocha/bin/mocha --timeout 160000 integration/blockchain.test.js -g 'Protocol versions'`

- Results:
```
  2 failing

  1) Blockchain Cluster
       Protocol versions
         rejects API calls with incorrect protoVer:
     Error: Timeout of 160000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/seo/git/comcomai/blockchain/ain-blockchain/integration/blockchain.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  2) Blockchain Cluster
       Protocol versions
         rejects API calls with no protoVer:
     Uncaught AssertionError: expected undefined to equal 1
      at /Users/seo/git/comcomai/blockchain/ain-blockchain/integration/blockchain.test.js:730:40
      at PromiseClientHttp.Client._parseResponse (node_modules/jayson/lib/client/index.js:209:10)
      at /Users/seo/git/comcomai/blockchain/ain-blockchain/node_modules/jayson/lib/client/index.js:140:10
      at Object.Utils.JSON.parse (node_modules/jayson/lib/utils.js:266:3)
      at IncomingMessage.<anonymous> (node_modules/jayson/lib/client/http.js:84:22)
      at endReadableNT (_stream_readable.js:1241:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21)



error Command failed with exit code 2.
```

**Comment by platfowner** [comment]
@minsulee2  Could you take a look? 
It seems it started to break since https://github.com/ainblockchain/ain-blockchain/pull/329 .

**Comment by minsulee2** [comment]
@platfowner Done with #342 Thanks for the notification :)
