### ISSUE TITLE
[BUG] error: [P2P_SERVER] TypeError: Invalid Version: 0.6

### ISSUE THREAD

**Issue by platfowner** [ainblockchain/ain-blockchain#345]
- How to reproduce:
```
rm -rf logs/; CONSOLE_LOG=true node tracker-server/index.js

rm -rf chains/; CONSOLE_LOG=true HOSTING_ENV=local DEBUG=false MIN_NUM_VALIDATORS=2 ACCOUNT_INDEX=0 ENABLE_DEV_CLIENT_API=true node client/index.js

CONSOLE_LOG=true HOSTING_ENV=local DEBUG=false MIN_NUM_VALIDATORS=2 ACCOUNT_INDEX=1 ENABLE_DEV_CLIENT_API=true node client/index.js 
```

- Error message:
```
2021-04-21T02:35:15.127Z [node-1-8082] error: [P2P_SERVER] TypeError: Invalid Version: 0.6
    at new SemVer (/Users/seo/git/comcomai/blockchain/ain-blockchain/node_modules/semver/semver.js:332:11)
    at compare (/Users/seo/git/comcomai/blockchain/ain-blockchain/node_modules/semver/semver.js:647:10)
    at Function.lt (/Users/seo/git/comcomai/blockchain/ain-blockchain/node_modules/semver/semver.js:688:10)
    at checkProtoVer (/Users/seo/git/comcomai/blockchain/ain-blockchain/p2p/util.js:126:37)
    at WebSocket.<anonymous> (/Users/seo/git/comcomai/blockchain/ain-blockchain/p2p/server.js:364:14)
    at WebSocket.emit (events.js:314:20)
    at Receiver.receiverOnMessage (/Users/seo/git/comcomai/blockchain/ain-blockchain/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.dataMessage (/Users/seo/git/comcomai/blockchain/ain-blockchain/node_modules/ws/lib/receiver.js:422:14)
    at Receiver.getData (/Users/seo/git/comcomai/blockchain/ain-blockchain/node_modules/ws/lib/receiver.js:352:17)
2021-04-21T02:35:15.130Z [node-1-8082] error: [P2P_SERVER] TypeError: Invalid Version: 0.6
    at new SemVer (/Users/seo/git/comcomai/blockchain/ain-blockchain/node_modules/semver/semver.js:332:11)
    at compare (/Users/seo/git/comcomai/blockchain/ain-blockchain/node_modules/semver/semver.js:647:10)
    at Function.lt (/Users/seo/git/comcomai/blockchain/ain-blockchain/node_modules/semver/semver.js:688:10)
    at checkProtoVer (/Users/seo/git/comcomai/blockchain/ain-blockchain/p2p/util.js:126:37)
    at WebSocket.<anonymous> (/Users/seo/git/comcomai/blockchain/ain-blockchain/p2p/server.js:364:14)
    at WebSocket.emit (events.js:314:20)
    at Receiver.receiverOnMessage (/Users/seo/git/comcomai/blockchain/ain-blockchain/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.dataMessage (/Users/seo/git/comcomai/blockchain/ain-blockchain/node_modules/ws/lib/receiver.js:422:14)
    at /Users/seo/git/comcomai/blockchain/ain-blockchain/node_modules/ws/lib/receiver.js:379:23

```

**Comment by platfowner** [comment]
아래 PR 이후로 발생하고 있습니다. @minsulee2  cc: @liayoo @cshcomcom 
https://github.com/ainblockchain/ain-blockchain/pull/343

**Comment by minsulee2** [comment]
Done!
