### ISSUE TITLE
[BUG] Sharding stopped working 

### ISSUE THREAD

**Issue by platfowner** [ainblockchain/ain-blockchain#368]
How to reproduce:
```
sh start_servers_afan.sh
```

Error message:
```
2021-04-28T06:56:29.783Z [node-0-9011] info: [P2P_SERVER] Setting up sharding..
2021-04-28T06:56:29.815Z [node-0-9011] error: [P2P_CLIENT] Error: Failed to sign and send tx: undefined
    at sendTxAndWaitForFinalization (/Users/seo/git/comcomai/blockchain/ain-blockchain/p2p/util.js:22:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async P2pServer.setUpDbForSharding (/Users/seo/git/comcomai/blockchain/ain-blockchain/p2p/server.js:608:5)
    at async P2pServer.tryInitializeShard (/Users/seo/git/comcomai/blockchain/ain-blockchain/p2p/server.js:598:7)
    at async WebSocket.<anonymous> (/Users/seo/git/comcomai/blockchain/ain-blockchain/p2p/index.js:169:13)

```

**Comment by platfowner** [comment]
```
2021-04-28T07:47:27.934Z [node-0-9011] error: [SERVER_UTIL] Failed to send transaction: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'ClientRequest'
    |     property 'socket' -> object with constructor 'Socket'
    --- property '_httpMessage' closes the circle
```

**Comment by platfowner** [comment]
```
{
  code: 16,
  error_message: 'Failed to collect gas fee: {\n' +
    '  "code": 103,\n' +
    '  "error_message": "No .write permission on: /gas_fee/collect/0x00Ba0Cb2B1157882963024E0CF837E773d11535d/24/0x97d53123aa1bf997b68ab2d895fbd7a365b7c8afb16558994b0b90fd3bf8dab3"\n' +
    '}'
}
```

**Comment by platfowner** [comment]
Fixed.
