### ISSUE TITLE
[BUG] error: uncaughtException: socket is not defined on shard nodes

### ISSUE THREAD

**Issue by platfowner** [ainblockchain/ain-blockchain#379]
@minsulee2  Could you take a look?

How to reproduce:
- git branch develop & git pull
- sh start_servers_afan.sh

Error log:
```
2021-05-10T03:31:26.019Z [node-0-9011] info: [CONSENSUS] [tryPropose] Already voted for 0x3ee5812df3b6e3248e9898f5cd20294cedf72c0e1e2bd1af03ff602d9acfe361 at epoch 16266055 but trying to propose at the same epoch
2021-05-10T03:31:27.299Z [node-0-9011] error: uncaughtException: socket is not defined
ReferenceError: socket is not defined
    at /Users/seo/git/comcomai/blockchain/ain-blockchain/p2p/index.js:508:11
    at Array.forEach (<anonymous>)
    at Timeout._onTimeout (/Users/seo/git/comcomai/blockchain/ain-blockchain/p2p/index.js:499:36)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
2021-05-10T03:31:27.299Z [node-0-9011] error: [CLIENT] ReferenceError: socket is not defined
2021-05-10T03:31:27.524Z [node-0-9011] info: [P2P_CLIENT] 
```

**Comment by platfowner** [comment]
@minsulee2  Thanks!
