### ISSUE TITLE
[BUG] Broken integration test in Github actions

### ISSUE THREAD

**Issue by minsulee2** [ainblockchain/ain-blockchain#382]
a part of afan_dapp.test.js is broken that 

```
SyntaxError: Unexpected token < in JSON at position 0
      at JSON.parse (<anonymous>)
      at /home/runner/work/ain-blockchain/ain-blockchain/unittest/test-util.js:85:29
      at Set.forEach (<anonymous>)
      at waitUntilTxFinalized (unittest/test-util.js:84:15)
      at setUp (integration/afan_dapp.test.js:89:8)
      at Context.<anonymous> (integration/afan_dapp.test.js:167:7)
      at processImmediate (internal/timers.js:456:21)
```

See also: https://github.com/ainblockchain/ain-blockchain/actions/runs/827250882

**Comment by minsulee2** [comment]
#389 can be one which make this problem. Test will soon begin! cc: @platfowner @liayoo @cshcomcom @shyun-comcom

**Comment by minsulee2** [comment]
Still await async is not working correctly. It should be applied for afan_dapp.test.js as well.
