### ISSUE TITLE
Broken unit tests with "TypeError: Cannot read property 'last_hash' of undefined"

### ISSUE THREAD

**Issue by platfowner** [ainblockchain/ain-blockchain#42]
```
./node_modules/mocha/bin/mocha --timeout 320000 -R  spec ./test/tx-pool.test.js

      1) "before each" hook for "transactions are correctly numbered"


  1 passing (56ms)
  1 failing

  1) TransactionPool
       sorting transactions by nonces
         "before each" hook for "transactions are correctly numbered":
     TypeError: Cannot read property 'last_hash' of undefined
      at Function.hasRequiredFields (blockchain/block.js:107:19)
      at Function.parse (blockchain/block.js:99:16)
      at Function.isValidChain (blockchain/index.js:163:30)
      at Function.loadChain (blockchain/index.js:329:20)
      at Blockchain.init (blockchain/index.js:59:33)
      at Node.init (node/index.js:31:46)
      at setDbForTesting (test/test-util.js:11:8)
      at Context.beforeEach (test/tx-pool.test.js:52:7)


./node_modules/mocha/bin/mocha --timeout 320000 -R  spec ./test/transaction.test.js

    1) "before each" hook for "assigns nonces correctly"


  0 passing (19ms)
  1 failing

  1) Transaction
       "before each" hook for "assigns nonces correctly":
     TypeError: Cannot read property 'last_hash' of undefined
      at Function.hasRequiredFields (blockchain/block.js:107:19)
      at Function.parse (blockchain/block.js:99:16)
      at Function.isValidChain (blockchain/index.js:163:30)
      at Function.loadChain (blockchain/index.js:329:20)
      at Blockchain.init (blockchain/index.js:59:33)
      at Node.init (node/index.js:31:46)
      at setDbForTesting (test/test-util.js:11:8)
      at Context.beforeEach (test/transaction.test.js:14:5)

```

**Comment by platfowner** [comment]
Now fixed in develop.
