### ISSUE TITLE
[BUG] sharding.test.js is broken with: TypeError: sendGetRequest is not a function

### ISSUE THREAD

**Issue by platfowner** [ainblockchain/ain-blockchain#421]
How to reproduce and error message:
```
$ yarn run test_sharding
yarn run v1.22.10
$ ./node_modules/mocha/bin/mocha --timeout 320000 integration/sharding.test.js


  Sharding
(node:53918) UnhandledPromiseRejectionWarning: TypeError: sendGetRequest is not a function
    at Function.getShardingAppConfig (/Users/seo/git/comcomai/blockchain/ain-blockchain/p2p/server.js:644:24)
    at P2pServer.setUpDbForSharding (/Users/seo/git/comcomai/blockchain/ain-blockchain/p2p/server.js:629:47)
    at P2pServer.tryInitializeShard (/Users/seo/git/comcomai/blockchain/ain-blockchain/p2p/server.js:614:18)
    at WebSocket.<anonymous> (/Users/seo/git/comcomai/blockchain/ain-blockchain/p2p/index.js:171:29)
    at WebSocket.emit (events.js:314:20)
    at Receiver.receiverOnMessage (/Users/seo/git/comcomai/blockchain/ain-blockchain/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.dataMessage (/Users/seo/git/comcomai/blockchain/ain-blockchain/node_modules/ws/lib/receiver.js:422:14)
    at Receiver.getData (/Users/seo/git/comcomai/blockchain/ain-blockchain/node_modules/ws/lib/receiver.js:352:17)
    at Receiver.startLoop (/Users/seo/git/comcomai/blockchain/ain-blockchain/node_modules/ws/lib/receiver.js:138:22)
(node:53918) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:53918) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by platfowner** [comment]
Fixed.
