### ISSUE TITLE
[BUG] broken test

### ISSUE THREAD

**Issue by platfowner** [ainblockchain/ain-blockchain#513]
@liayoo could you take a look at the broken test with message:
```
$ yarn run test_integration_node -g 'write rule: auth.fid: with function permission'
yarn run v1.22.10
$ ./node_modules/mocha/bin/mocha --timeout 160000 integration/node.test.js -g 'write rule: auth.fid: with function permission'


  Blockchain Node
    Function triggering
      Function permission
        Write rule: auth.fid
          1) write rule: auth.fid: with function permission


  0 passing (25s)
  1 failing

  1) Blockchain Node
       Function triggering
         Function permission
           Write rule: auth.fid
             write rule: auth.fid: with function permission:

      AssertionError: expected { Object (func_results, code, ...) } to deeply equal { Object (code, func_results, ...) }
      + expected - actual

             "service": 0
           }
           "state": {
             "app": {
      -        "test": 1516
      +        "test": 1348
             }
      -      "service": 16
      +      "service": 0
           }
         }
         "gas_cost_total": 0
       }
      
      at Context.<anonymous> (integration/node.test.js:3537:18)
      at processImmediate (internal/timers.js:461:21)
```

**Comment by liayoo** [comment]
Fixed in https://github.com/ainblockchain/ain-blockchain/pull/514
