### ISSUE TITLE
[BUG] Empty label radix 

### ISSUE THREAD

**Issue by platfowner** [ainblockchain/ain-blockchain#552]
'Overwriting a child' with empty label radix:
```
2021-09-01T18:04:16.189Z [node-0-8081] error: [RADIX_TREE] AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA labelSuffix: 6f6d656f6e, childLabelSuffix: 6f6d656f6e6e6e6e6e6e6e, commonPrefix: 6f6d656f6e, childNewLabel: 6e6e6e6e6e6e, newChildLabel:
2021-09-01T18:04:16.190Z [node-0-8081] error: [RADIX_NODE] [setChild] Overwriting a child with radix label  at: Error
    at RadixNode.setChild (/Users/seo/git/comcomai/blockchain/ain-blockchain/db/radix-node.js:111:18)
    at RadixTree._getRadixNodeForWriting (/Users/seo/git/comcomai/blockchain/ain-blockchain/db/radix-tree.js:113:22)
    at RadixTree._setInTree (/Users/seo/git/comcomai/blockchain/ain-blockchain/db/radix-tree.js:150:23)
    at RadixTree.set (/Users/seo/git/comcomai/blockchain/ain-blockchain/db/radix-tree.js:160:15)
    at StateNode.setChild (/Users/seo/git/comcomai/blockchain/ain-blockchain/db/state-node.js:262:22)
    at Function.getRefForWritingToStateRoot (/Users/seo/git/comcomai/blockchain/ain-blockchain/db/index.js:365:16)
    at Function.writeToStateRoot (/Users/seo/git/comcomai/blockchain/ain-blockchain/db/index.js:395:25)
    at DB.writeDatabase (/Users/seo/git/comcomai/blockchain/ain-blockchain/db/index.js:410:25)
    at DB.setValue (/Users/seo/git/comcomai/blockchain/ain-blockchain/db/index.js:706:10)
    at DB.executeSingleSetOperation (/Users/seo/git/comcomai/blockchain/ain-blockchain/db/index.js:882:23).
2021-09-01T18:04:17.326Z [node-0-8081] error: [RADIX_TREE] AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA labelSuffix: 6f6d656f6e, childLabelSuffix: 6f6d656f6e6e6e6e6e6e6e, commonPrefix: 6f6d656f6e, childNewLabel: 6e6e6e6e6e6e, newChildLabel:
2021-09-01T18:04:17.326Z [node-0-8081] error: [RADIX_NODE] [setChild] Overwriting a child with radix label  at: Error
    at RadixNode.setChild (/Users/seo/git/comcomai/blockchain/ain-blockchain/db/radix-node.js:111:18)
    at RadixTree._getRadixNodeForWriting (/Users/seo/git/comcomai/blockchain/ain-blockchain/db/radix-tree.js:113:22)
    at RadixTree._setInTree (/Users/seo/git/comcomai/blockchain/ain-blockchain/db/radix-tree.js:150:23)
    at RadixTree.set (/Users/seo/git/comcomai/blockchain/ain-blockchain/db/radix-tree.js:160:15)
    at StateNode.setChild (/Users/seo/git/comcomai/blockchain/ain-blockchain/db/state-node.js:262:22)
    at Function.getRefForWritingToStateRoot (/Users/seo/git/comcomai/blockchain/ain-blockchain/db/index.js:365:16)
    at Function.writeToStateRoot (/Users/seo/git/comcomai/blockchain/ain-blockchain/db/index.js:395:25)
    at DB.writeDatabase (/Users/seo/git/comcomai/blockchain/ain-blockchain/db/index.js:410:25)
    at DB.setValue (/Users/seo/git/comcomai/blockchain/ain-blockchain/db/index.js:706:10)
    at DB.executeSingleSetOperation (/Users/seo/git/comcomai/blockchain/ain-blockchain/db/index.js:882:23).
```

**Comment by platfowner** [comment]
Fixed.
