### ISSUE TITLE
[BUG] Updating proof hash for non-existing child with label

### ISSUE THREAD

**Issue by platfowner** [ainblockchain/ain-blockchain#554]
Error logs 'Updating proof hash for non-existing child with label' observed when running integration tests:

```
yarn run test_integration_node
```

```
2021-09-02T03:26:03.675Z [node-0-8081] error: [RADIX_TREE] [updateProofHashForRadixPath] Updating proof hash for non-existing child with label: test_value at: Error
    at RadixTree.updateProofHashForRadixPath (/Users/seo/git/comcomai/blockchain/ain-blockchain/db/radix-tree.js:308:38)
    at StateNode.buildProofHash (/Users/seo/git/comcomai/blockchain/ain-blockchain/db/state-node.js:391:26)
    at StateNode.updateProofHashAndStateInfo (/Users/seo/git/comcomai/blockchain/ain-blockchain/db/state-node.js:458:28)
    at updateProofHashForAllRootPathsRecursive (/Users/seo/git/comcomai/blockchain/ain-blockchain/db/state-util.js:629:10)
    at updateProofHashForAllRootPaths (/Users/seo/git/comcomai/blockchain/ain-blockchain/db/state-util.js:665:10)
    at Function.writeToStateRoot (/Users/seo/git/comcomai/blockchain/ain-blockchain/db/index.js:404:7)
    at DB.writeDatabase (/Users/seo/git/comcomai/blockchain/ain-blockchain/db/index.js:410:25)
    at DB.setValue (/Users/seo/git/comcomai/blockchain/ain-blockchain/db/index.js:706:10)
    at DB.executeSingleSetOperation (/Users/seo/git/comcomai/blockchain/ain-blockchain/db/index.js:882:23)
    at DB.executeMultiSetOperation (/Users/seo/git/comcomai/blockchain/ain-blockchain/db/index.js:909:27).
```

**Comment by platfowner** [comment]
Fixed by empty node removal code re-implementation.
