### ISSUE TITLE
[BUG] JavaScript heap out of memory

### ISSUE THREAD

**Issue by platfowner** [ainblockchain/ain-blockchain#588]
```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parse (/home/ain-blockchain/node_modules/body-parser/lib/types/json.js:89:19)
    at /home/ain-blockchain/node_modules/body-parser/lib/read.js:121:18
    at invokeCallback (/home/ain-blockchain/node_modules/raw-body/index.js:224:16)
    at done (/home/ain-blockchain/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/home/ain-blockchain/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:314:20)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory
 1: 0xa1a640 node::Abort() [node]
 2: 0xa1aa4c node::OnFatalError(char const*, char const*) [node]
 3: 0xb9a62e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb9a9a9 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xd57c25  [node]
 6: 0xd2fab0 v8::internal::Factory::NewFixedArrayWithHoles(int, v8::internal::AllocationType) [node]
 7: 0x110512a v8::internal::FixedArrayBuilder::EnsureCapacity(v8::internal::Isolate*, int) [node]
 8: 0x1095dfc  [node]
 9: 0x1097c91 v8::internal::Runtime_RegExpExecMultiple(int, unsigned long*, v8::internal::Isolate*) [node]
10: 0x140dc19  [node]
```

**Comment by platfowner** [comment]
After reducing MAX_OLD_SPACE_SIZE_MB to 5500, it's not observed yet.

![Screen Shot 2021-09-29 at 10 03 00 AM](https://user-images.githubusercontent.com/46211617/135185590-1401cb09-424a-4380-ac57-b7809af1e3b3.jpg)


![Screen Shot 2021-09-29 at 9 58 58 AM](https://user-images.githubusercontent.com/46211617/135185393-b5dfb696-0032-4ac4-8788-c4458a289707.jpg)

**Comment by platfowner** [comment]
Resolved.
