### ISSUE TITLE
[BUG] Broken consensus integration tests

### ISSUE THREAD

**Issue by platfowner** [ainblockchain/ain-blockchain#595]
Test run logs:
```
$ yarn run test_integration_consensus
yarn run v1.22.10
$ ./node_modules/mocha/bin/mocha --timeout 640000 integration/consensus.test.js


  Consensus
Iteration count exceeded its limit before the network is ready (["http://localhost:8085"])
    Validators
Iteration count exceeded its limit before the given tx 0x9e555ecd3789ea90c25689762c90c7d8b2e03fb9ca6c6751a07c24522e433289 is finalized!
Failed to check finalization of server5's staking tx.
Iteration count exceeded its limit before server5 becomes a validator
      1) Number of validators cannot exceed MAX_NUM_VALIDATORS
      2) When more than MAX_NUM_VALIDATORS validators exist, validatators with bigger stakes get prioritized
    Rewards
Iteration count exceeded its limit before the given tx 0xf922905fc609e99bb6ebe42e729f4886ea1dca42f3ba1469ca4e026600a73b0d is finalized!
Failed to check finalization of tx.
      ✓ consensus rewards are updated (103626ms)
Iteration count exceeded its limit before the given tx 0x502868756a37be8e0017f7054bba34cb680ee048bcee9243b787df3df05d0f5f is finalized!
Failed to check finalization of tx.
      ✓ cannot claim more than unclaimed rewards (102604ms)
Iteration count exceeded its limit before the given tx 0xdc937ea779d02ee22c71ae8ee76f49a780a424fdb09e47ef65c7a67966bf7c9c is finalized!
Failed to check finalization of tx.
      ✓ can claim unclaimed rewards (102346ms)
    Penalties
      ✓ can record an offense and its evidence (11303ms)
      ✓ can penalize malicious validators  (9079ms)


  5 passing (12m)
  2 failing

  1) Consensus
       Validators
         Number of validators cannot exceed MAX_NUM_VALIDATORS:
     AssertionError: server5 is not included in validators
      at Context.<anonymous> (integration/consensus.test.js:229:18)

  2) Consensus
       Validators
         When more than MAX_NUM_VALIDATORS validators exist, validatators with bigger stakes get prioritized:

      AssertionError: expected 100000 to deeply equal 100010
      + expected - actual

      -100000
      +100010
      
      at Context.<anonymous> (integration/consensus.test.js:274:14)



error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by liayoo** [comment]
Fixed by #601
