### ISSUE TITLE
[BUG] Unhandled promise rejection

### ISSUE THREAD

**Issue by platfowner** [ainblockchain/ain-blockchain#598]
```
(node:1800) UnhandledPromiseRejectionWarning: Error: Total timeout of API google.logging.v2.LoggingServiceV2 exceed
ed 60000 milliseconds before any response was received.
    at repeat (/home/ain-blockchain/node_modules/google-gax/build/src/normalCalls/retries.js:66:31)
    at Timeout._onTimeout (/home/ain-blockchain/node_modules/google-gax/build/src/normalCalls/retries.js:101:25)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:1800) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing
 inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). 
To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see
 https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1800) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejec
tions that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1800) UnhandledPromiseRejectionWarning: Error: Total timeout of API google.logging.v2.LoggingServiceV2 exceed
ed 60000 milliseconds before any response was received.
    at repeat (/home/ain-blockchain/node_modules/google-gax/build/src/normalCalls/retries.js:66:31)
    at Timeout._onTimeout (/home/ain-blockchain/node_modules/google-gax/build/src/normalCalls/retries.js:101:25)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:1800) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing
 inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). 
To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see
 https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1800) UnhandledPromiseRejectionWarning: Error: Total timeout of API google.logging.v2.LoggingServiceV2 exceed
ed 60000 milliseconds before any response was received.
    at repeat (/home/ain-blockchain/node_modules/google-gax/build/src/normalCalls/retries.js:66:31)
    at Timeout._onTimeout (/home/ain-blockchain/node_modules/google-gax/build/src/normalCalls/retries.js:101:25)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:1800) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing
 inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). 
To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see
 https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
```

ref: https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode

**Comment by platfowner** [comment]
Not reproducible.
