### ISSUE TITLE
[BUG] Flaky p2p unit tests 

### ISSUE THREAD

**Issue by platfowner** [ainblockchain/ain-blockchain#609]
Sometimes some p2p unit tests break.

Logs:
```
yarn run test_unit
yarn run v1.22.10
$ ACCOUNT_INDEX=0 MIN_NUM_VALIDATORS=1 STATE_TREE_BYTES_LIMIT=20000000 ./node_modules/mocha/bin/mocha --timeout 160000 "unittest/*.test.js"

...

  P2P
    Server Status
      getIpAddress
        ✓ gets ip address
      setUpIpAddresses
p2pServer.node.ipAddrInternal 192.168.35.208 true
p2pServer.node.ipAddrExternal 39.115.187.190 true
        ✓ sets ip address
      getNodeAddress
        ✓ gets node address
      getNodePrivateKey
        ✓ gets node private key address
      getExternalIp
        ✓ gets external IP address
      getProtocolInfo
        ✓ gets external IP address
      getStateVersionStatus
        1) gets initial state version status
      getConsensusStatus
        ✓ gets initial consensus state
      getBlockStatus
        2) gets initial block status
      getNodeStatus
        3) gets initial node status
      getDiskUsage
        ✓ gets initial disk usage (it depends on the machine)

...

  600 passing (37s)
  3 failing

  1) P2P
       Server Status
         getStateVersionStatus
           gets initial state version status:

      AssertionError: expected { Object (numVersions, versionList, ...) } to deeply equal { Object (numVersions, versionList, ...) }
      + expected - actual

       {
      -  "finalVersion": "FINAL:260"
      +  "finalVersion": "FINAL:0"
         "numVersions": 3
         "versionList": [
           "EMPTY"
      -    "FINAL:260"
      -    "NODE:260"
      +    "FINAL:0"
      +    "NODE:0"
         ]
       }
      
      at Context.<anonymous> (unittest/p2p.test.js:95:16)
      at processImmediate (internal/timers.js:461:21)

  2) P2P
       Server Status
         getBlockStatus
           gets initial block status:

      AssertionError: expected { Object (number, epoch, ...) } to deeply equal { Object (number, epoch, ...) }
      + expected - actual

       {
      -  "epoch": 20715453
      -  "number": 260
      -  "timestamp": 1633965678607
      +  "epoch": 0
      +  "number": 0
      +  "timestamp": 1571819318272
       }
      
      at Context.<anonymous> (unittest/p2p.test.js:121:16)
      at processImmediate (internal/timers.js:461:21)

  3) P2P
       Server Status
         getNodeStatus
           gets initial node status:

      AssertionError: expected { Object (address, state, ...) } to deeply equal { Object (address, state, ...) }
      + expected - actual

             "#state_ph": "erased"
             "#tree_bytes": "erased"
             "#tree_height": 11
             "#tree_size": "erased"
      -      "#version": "NODE:260"
      +      "#version": "NODE:0"
           }
           "stateProof": {
             "#state_ph": "erased"
           }
--
         "nonce": 0
         "state": "SYNCING"
         "stateNumeric": 1
         "stateVersionStatus": {
      -    "finalVersion": "FINAL:260"
      +    "finalVersion": "FINAL:0"
           "numVersions": 3
           "versionList": [
             "EMPTY"
      -      "FINAL:260"
      -      "NODE:260"
      +      "FINAL:0"
      +      "NODE:0"
           ]
         }
       }
      
      at Context.<anonymous> (unittest/p2p.test.js:134:16)
      at processImmediate (internal/timers.js:461:21)



error Command failed with exit code 3.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by platfowner** [comment]
Fixed.
