### ISSUE TITLE
[BUG] "No notarized block" error in restarting

### ISSUE THREAD

**Issue by platfowner** [ainblockchain/ain-blockchain#687]
Branch:
https://github.com/ainblockchain/ain-blockchain/pull/684

How to reproduce:
```bash start_node_genesis_gcp.sh summer 0 0 --keep-code```

Error logs:
```
2021-11-15T10:20:29.621Z [node-0-8080] error: [NODE] [loadAndExecuteChainOnDb] Failed to validate and execute block
 10001: ConsensusException: No notarized block at number 10000 with hash 0x832084c910d27b3c0db9662177d9b1188f04fd26
b395e9f7d22c70da9db8ee8b
    at Function.getPrevBlockInfo (/home/ain-blockchain/consensus/index.js:458:13)
    at Function.validateAndExecuteBlockOnDb (/home/ain-blockchain/consensus/index.js:767:37)
    at BlockchainNode.loadAndExecuteChainOnDb (/home/ain-blockchain/node/index.js:526:19)
    at BlockchainNode.init (/home/ain-blockchain/node/index.js:207:17)
    at P2pClient.startBlockchainNode (/home/ain-blockchain/p2p/index.js:272:29)
    at WebSocket.<anonymous> (/home/ain-blockchain/p2p/index.js:232:24)
    at WebSocket.emit (events.js:314:20)
    at Receiver.receiverOnMessage (/home/ain-blockchain/node_modules/ws/lib/websocket.js:983:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.dataMessage (/home/ain-blockchain/node_modules/ws/lib/receiver.js:517:14)
Error
    at Function.logErrorWithStackTrace (/home/ain-blockchain/common/common-util.js:664:33)
    at Function.finishWithStackTrace (/home/ain-blockchain/common/common-util.js:674:16)
    at BlockchainNode.loadAndExecuteChainOnDb (/home/ain-blockchain/node/index.js:534:20)
    at BlockchainNode.init (/home/ain-blockchain/node/index.js:207:17)
    at P2pClient.startBlockchainNode (/home/ain-blockchain/p2p/index.js:272:29)
    at WebSocket.<anonymous> (/home/ain-blockchain/p2p/index.js:232:24)
    at WebSocket.emit (events.js:314:20)
    at Receiver.receiverOnMessage (/home/ain-blockchain/node_modules/ws/lib/websocket.js:983:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.dataMessage (/home/ain-blockchain/node_modules/ws/lib/receiver.js:517:14).
```

**Comment by platfowner** [comment]
In local tests, the following error messages are seen:
```
2021-11-15T13:08:55.173Z [node-1-8082] info: [P2P_CLIENT] [startBlockchainNode] Starting blockchain node with 1 peers..
2021-11-15T13:08:55.173Z [node-1-8082] info: [NODE] [initNode] Initializing node in 'fast' mode..
2021-11-15T13:08:55.177Z [node-1-8082] info: [NODE] [initNode] Fast mode DB snapshot loading done!
2021-11-15T13:08:55.177Z [node-1-8082] info: [NODE] [initNode] Initializing DB..
2021-11-15T13:08:55.260Z [node-1-8082] info: [NODE] [initNode] Initializing blockchain..
2021-11-15T13:08:55.261Z [node-1-8082] info: [BLOCKCHAIN] 

2021-11-15T13:08:55.261Z [node-1-8082] info: [BLOCKCHAIN] ################################################################
2021-11-15T13:08:55.261Z [node-1-8082] info: [BLOCKCHAIN] ## Starting NON-FIRST-NODE blockchain with EXISTING blocks... ##
2021-11-15T13:08:55.261Z [node-1-8082] info: [BLOCKCHAIN] ################################################################
2021-11-15T13:08:55.261Z [node-1-8082] info: [BLOCKCHAIN] 

2021-11-15T13:08:55.261Z [node-1-8082] info: [NODE] [initNode] Executing chains on DB if needed..
2021-11-15T13:08:55.265Z [node-1-8082] info: [NODE] [loadAndExecuteChainOnDb] Successfully loaded block: 10 / 21720751
2021-11-15T13:08:55.266Z [node-1-8082] info: [BLOCK_POOL] [addSeenBlock] Adding seen block to the block pool: 0xea8ee89dd1c7ee82abd20daccdc5a2fcb4b429581383533cc674a707a5adde69 / 10 / 21720751 / true
2021-11-15T13:08:55.266Z [node-1-8082] info: [BLOCK_POOL] [addToHashBlockInfoMap] Block added to the block pool: 10 / 21720751
2021-11-15T13:08:55.269Z [node-1-8082] info: [NODE] [loadAndExecuteChainOnDb] Successfully loaded block: 11 / 21720752
2021-11-15T13:08:55.272Z [node-1-8082] info: [CONSENSUS] Proposer is 0x00ADEc28B6a845a085e03591bE7550dd68673C1C
2021-11-15T13:08:55.277Z [node-1-8082] info: [BLOCK_POOL] [tryUpdateNotarized] Notarized block: 0xea8ee89dd1c7ee82abd20daccdc5a2fcb4b429581383533cc674a707a5adde69 (10 / 21720751)
2021-11-15T13:08:55.278Z [node-1-8082] error: [NODE] [loadAndExecuteChainOnDb] Failed to validate and execute block 11: TypeError: Cannot read property 'hash' of null
    at BlockPool.getLongestNotarizedChainList (/Users/seo/git/comcomai/blockchain/ain-blockchain/block-pool/index.js:98:60)
    at BlockPool.updateLongestNotarizedChains (/Users/seo/git/comcomai/blockchain/ain-blockchain/block-pool/index.js:50:32)
    at BlockPool.tryUpdateNotarized (/Users/seo/git/comcomai/blockchain/ain-blockchain/block-pool/index.js:454:12)
    at BlockPool.addVoteFor (/Users/seo/git/comcomai/blockchain/ain-blockchain/block-pool/index.js:387:12)
    at BlockPool.addSeenVote (/Users/seo/git/comcomai/blockchain/ain-blockchain/block-pool/index.js:360:12)
    at Function.validateAndExecuteLastVotes (/Users/seo/git/comcomai/blockchain/ain-blockchain/consensus/index.js:572:17)
    at Function.validateAndExecuteBlockOnDb (/Users/seo/git/comcomai/blockchain/ain-blockchain/consensus/index.js:779:17)
    at BlockchainNode.loadAndExecuteChainOnDb (/Users/seo/git/comcomai/blockchain/ain-blockchain/node/index.js:540:21)
    at BlockchainNode.initNode (/Users/seo/git/comcomai/blockchain/ain-blockchain/node/index.js:207:17)
    at P2pClient.startBlockchainNode (/Users/seo/git/comcomai/blockchain/ain-blockchain/p2p/index.js:280:29)
Error
    at Function.logErrorWithStackTrace (/Users/seo/git/comcomai/blockchain/ain-blockchain/common/common-util.js:664:33)
    at Function.finishWithStackTrace (/Users/seo/git/comcomai/blockchain/ain-blockchain/common/common-util.js:674:16)
    at BlockchainNode.loadAndExecuteChainOnDb (/Users/seo/git/comcomai/blockchain/ain-blockchain/node/index.js:549:20)
    at BlockchainNode.initNode (/Users/seo/git/comcomai/blockchain/ain-blockchain/node/index.js:207:17)
    at P2pClient.startBlockchainNode (/Users/seo/git/comcomai/blockchain/ain-blockchain/p2p/index.js:280:29)
    at WebSocket.<anonymous> (/Users/seo/git/comcomai/blockchain/ain-blockchain/p2p/index.js:240:24)
    at WebSocket.emit (events.js:314:20)
    at Receiver.receiverOnMessage (/Users/seo/git/comcomai/blockchain/ain-blockchain/node_modules/ws/lib/websocket.js:834:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.dataMessage (/Users/seo/git/comcomai/blockchain/ain-blockchain/node_modules/ws/lib/receiver.js:437:14).
```

**Comment by platfowner** [comment]
Trying to fix it by adding the last block to the snapshot.. @liayoo
