### ISSUE TITLE
Test fails with 'error: uncaughtException: connect ECONNREFUSED 127.0.0.1:8081'

### ISSUE THREAD

**Issue by platfowner** [ainblockchain/ain-blockchain#70]
`./node_modules/mocha/bin/mocha --timeout 320000 -R  spec ./integration/dev.test.js`

```
2020-08-26T10:36:19.437Z [node-null] error: uncaughtException: connect ECONNREFUSED 127.0.0.1:8081
Error: connect ECONNREFUSED 127.0.0.1:8081
    at extractValue (/Users/seo/git/comcomai/blockchain/ain-blockchain/node_modules/sync-rpc/lib/index.js:165:19)
    at /Users/seo/git/comcomai/blockchain/ain-blockchain/node_modules/sync-rpc/lib/index.js:175:12
    at request (/Users/seo/git/comcomai/blockchain/ain-blockchain/node_modules/sync-request/lib/index.js:28:15)
    at Suite.describe (/Users/seo/git/comcomai/blockchain/ain-blockchain/integration/dev.test.js:243:31)
    at Object.create (/Users/seo/git/comcomai/blockchain/ain-blockchain/node_modules/mocha/lib/interfaces/common.js:140:19)
    at context.describe.context.context (/Users/seo/git/comcomai/blockchain/ain-blockchain/node_modules/mocha/lib/interfaces/bdd.js:42:27)
    at Suite.describe (/Users/seo/git/comcomai/blockchain/ain-blockchain/integration/dev.test.js:242:5)
    at Object.create (/Users/seo/git/comcomai/blockchain/ain-blockchain/node_modules/mocha/lib/interfaces/common.js:140:19)
    at context.describe.context.context (/Users/seo/git/comcomai/blockchain/ain-blockchain/node_modules/mocha/lib/interfaces/bdd.js:42:27)
    at Suite.describe (/Users/seo/git/comcomai/blockchain/ain-blockchain/integration/dev.test.js:174:3)
    at Object.create (/Users/seo/git/comcomai/blockchain/ain-blockchain/node_modules/mocha/lib/interfaces/common.js:140:19)
    at context.describe.context.context (/Users/seo/git/comcomai/blockchain/ain-blockchain/node_modules/mocha/lib/interfaces/bdd.js:42:27)
    at Object.<anonymous> (/Users/seo/git/comcomai/blockchain/ain-blockchain/integration/dev.test.js:146:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at /Users/seo/git/comcomai/blockchain/ain-blockchain/node_modules/mocha/lib/mocha.js:334:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/seo/git/comcomai/blockchain/ain-blockchain/node_modules/mocha/lib/mocha.js:331:14)
    at Mocha.run (/Users/seo/git/comcomai/blockchain/ain-blockchain/node_modules/mocha/lib/mocha.js:809:10)
    at Object.exports.singleRun (/Users/seo/git/comcomai/blockchain/ain-blockchain/node_modules/mocha/lib/cli/run-helpers.js:108:16)
    at exports.runMocha (/Users/seo/git/comcomai/blockchain/ain-blockchain/node_modules/mocha/lib/cli/run-helpers.js:142:13)
    at Object.exports.handler.argv [as handler] (/Users/seo/git/comcomai/blockchain/ain-blockchain/node_modules/mocha/lib/cli/run.js:292:3)
    at Object.runCommand (/Users/seo/git/comcomai/blockchain/ain-blockchain/node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] (/Users/seo/git/comcomai/blockchain/ain-blockchain/node_modules/yargs/yargs.js:1096:28)
    at Object.parse (/Users/seo/git/comcomai/blockchain/ain-blockchain/node_modules/yargs/yargs.js:575:25)
    at Object.exports.main (/Users/seo/git/comcomai/blockchain/ain-blockchain/node_modules/mocha/lib/cli/cli.js:68:6)
    at Object.<anonymous> (/Users/seo/git/comcomai/blockchain/ain-blockchain/node_modules/mocha/bin/mocha:162:29)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

**Comment by seunghokimj** [comment]
Issue fixed
