### ISSUE TITLE
[BUG] Error: Cannot find module 'winston'

### ISSUE THREAD

**Issue by platfowner** [ainblockchain/ain-blockchain#715]
Deploy command line:
```
bash deploy_blockchain_genesis_gcp.sh staging seo 0
```

error_logs.txt:
```
internal/modules/cjs/loader.js:818
  throw err;
  ^
Error: Cannot find module 'winston'
Require stack:
- /home/ain-blockchain/logger/index.js
- /home/ain-blockchain/client/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/ain-blockchain/logger/index.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/ain-blockchain/logger/index.js',
    '/home/ain-blockchain/client/index.js'
  ]
}
```

**Comment by platfowner** [comment]
Notably this happens for the tracker server as well.

**Comment by platfowner** [comment]
node module installation error:
```
Installing node modules..
yarn install v1.22.17
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning @ainblockchain/ain-util > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning ext-ip > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning ext-ip > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning ext-ip > request > har-validator@5.1.5: this library is no longer supported
warning jayson > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning chai-http > superagent > formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
warning node-jq > tempfile > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning node-jq > strip-eof@2.0.0: Renamed to `strip-final-newline` to better represent its functionality.
warning node-jq > bin-build > tempfile > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning semistandard > eslint > file-entry-cache > flat-cache > circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
[3/5] Fetching packages...
error @semantic-release/git@10.0.1: The engine "node" is incompatible with this module. Expected version ">=14.17". Got "12.22.7"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error Found incompatible module.
```

**Comment by platfowner** [comment]
Fixed.
