### ISSUE TITLE
GCP logging error

### ISSUE THREAD

**Issue by liayoo** [ainblockchain/ain-blockchain#745]
In some of the testnet-sandbox nodes, the following error logs have been observed (in error_logs.txt)

```
(node:11314) UnhandledPromiseRejectionWarning: Error: Total timeout of API google.logging.v2.LoggingServiceV2 exceeded 60000 milliseconds before any response was received.
    at repeat (/home/ain-blockchain/node_modules/google-gax/build/src/normalCalls/retries.js:66:31)
    at Timeout._onTimeout (/home/ain-blockchain/node_modules/google-gax/build/src/normalCalls/retries.js:101:25)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:11314) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11314) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by platfowner** [comment]
error_logs.txt of summer node-1 in R48:
```
SyntaxError: Unexpected token @ in JSON at position 0
    at JSON.parse (<anonymous>)
    at createStrictSyntaxError (/home/ain-blockchain/node_modules/body-parser/lib/types/json.js:158:10)
    at parse (/home/ain-blockchain/node_modules/body-parser/lib/types/json.js:83:15)
    at /home/ain-blockchain/node_modules/body-parser/lib/read.js:121:18
    at invokeCallback (/home/ain-blockchain/node_modules/raw-body/index.js:224:16)
    at done (/home/ain-blockchain/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/home/ain-blockchain/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:314:20)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
SyntaxError: Unexpected token u in JSON at position 1
    at JSON.parse (<anonymous>)
    at parse (/home/ain-blockchain/node_modules/body-parser/lib/types/json.js:89:19)
    at /home/ain-blockchain/node_modules/body-parser/lib/read.js:121:18
    at invokeCallback (/home/ain-blockchain/node_modules/raw-body/index.js:224:16)
    at done (/home/ain-blockchain/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/home/ain-blockchain/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:314:20)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
SyntaxError: Unexpected token { in JSON at position 131
    at JSON.parse (<anonymous>)
    at parse (/home/ain-blockchain/node_modules/body-parser/lib/types/json.js:89:19)
    at /home/ain-blockchain/node_modules/body-parser/lib/read.js:121:18
    at invokeCallback (/home/ain-blockchain/node_modules/raw-body/index.js:224:16)
    at done (/home/ain-blockchain/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/home/ain-blockchain/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:314:20)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:17932) UnhandledPromiseRejectionWarning: Error: Total timeout of API google.logging.v2.LoggingServiceV2 excee
ded 60000 milliseconds before any response was received.
    at repeat (/home/ain-blockchain/node_modules/google-gax/build/src/normalCalls/retries.js:66:31)
    at Timeout._onTimeout (/home/ain-blockchain/node_modules/google-gax/build/src/normalCalls/retries.js:101:25)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:17932) UnhandledPromiseRejectionWarning: Error: Total timeout of API google.logging.v2.LoggingServiceV2 excee
ded 60000 milliseconds before any response was received.
    at repeat (/home/ain-blockchain/node_modules/google-gax/build/src/normalCalls/retries.js:66:31)
    at Timeout._onTimeout (/home/ain-blockchain/node_modules/google-gax/build/src/normalCalls/retries.js:101:25)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:17932) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwin
g inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
 To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (se
e https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17932) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise reje
ctions that are not handled will terminate the Node.js process with a non-zero exit code.
(node:17932) UnhandledPromiseRejectionWarning: Error: Total timeout of API google.logging.v2.LoggingServiceV2 excee
ded 60000 milliseconds before any response was received.
    at repeat (/home/ain-blockchain/node_modules/google-gax/build/src/normalCalls/retries.js:66:31)
    at Timeout._onTimeout (/home/ain-blockchain/node_modules/google-gax/build/src/normalCalls/retries.js:101:25)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
...
```
<img width="1049" alt="Screen Shot 2021-12-08 at 1 59 13 AM" src="https://user-images.githubusercontent.com/46211617/145073193-e5af4077-0eca-4dc2-9ecc-88d35c7e214e.png">

<img width="1055" alt="Screen Shot 2021-12-08 at 2 00 24 AM" src="https://user-images.githubusercontent.com/46211617/145073204-6c4b334a-f7d4-49dd-8b3c-e9559a7d71f0.png">

**Comment by platfowner** [comment]
@liayoo @minsulee2 just took a look at the abnormality of summer node-1 and realized that it's the known logger issue.

**Comment by platfowner** [comment]
Recently summer node-0 died with the followiging error_logs.txt:
```
express-rate-limit: req.ip is undefined - you can avoid this by providing a custom keyGenerator function, but it ma
y be indicative of a larger issue.
SyntaxError: Unexpected token @ in JSON at position 0
    at JSON.parse (<anonymous>)
    at createStrictSyntaxError (/home/ain-blockchain/node_modules/body-parser/lib/types/json.js:158:10)
    at parse (/home/ain-blockchain/node_modules/body-parser/lib/types/json.js:83:15)
    at /home/ain-blockchain/node_modules/body-parser/lib/read.js:121:18
    at invokeCallback (/home/ain-blockchain/node_modules/raw-body/index.js:224:16)
    at done (/home/ain-blockchain/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/home/ain-blockchain/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:314:20)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
SyntaxError: Unexpected token u in JSON at position 1
    at JSON.parse (<anonymous>)
    at parse (/home/ain-blockchain/node_modules/body-parser/lib/types/json.js:89:19)
    at /home/ain-blockchain/node_modules/body-parser/lib/read.js:121:18
    at invokeCallback (/home/ain-blockchain/node_modules/raw-body/index.js:224:16)
    at done (/home/ain-blockchain/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/home/ain-blockchain/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:314:20)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
SyntaxError: Unexpected token { in JSON at position 131
    at JSON.parse (<anonymous>)
    at parse (/home/ain-blockchain/node_modules/body-parser/lib/types/json.js:89:19)
    at /home/ain-blockchain/node_modules/body-parser/lib/read.js:121:18
    at invokeCallback (/home/ain-blockchain/node_modules/raw-body/index.js:224:16)
    at done (/home/ain-blockchain/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/home/ain-blockchain/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:314:20)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
BadRequestError: request aborted
    at IncomingMessage.onAborted (/home/ain-blockchain/node_modules/raw-body/index.js:231:10)
    at IncomingMessage.emit (events.js:314:20)
    at abortIncoming (_http_server.js:533:9)
    at socketOnClose (_http_server.js:526:3)
    at Socket.emit (events.js:326:22)
    at TCP.<anonymous> (net.js:675:12)
BadRequestError: request aborted
    at IncomingMessage.onAborted (/home/ain-blockchain/node_modules/raw-body/index.js:231:10)
    at IncomingMessage.emit (events.js:314:20)
    at abortIncoming (_http_server.js:533:9)
    at socketOnClose (_http_server.js:526:3)
    at Socket.emit (events.js:326:22)
    at TCP.<anonymous> (net.js:675:12)
express-rate-limit: req.ip is undefined - you can avoid this by providing a custom keyGenerator function, but it ma
y be indicative of a larger issue.
(node:15736) UnhandledPromiseRejectionWarning: Error: Total timeout of API google.logging.v2.LoggingServiceV2 excee
ded 60000 milliseconds before any response was received.
    at repeat (/home/ain-blockchain/node_modules/google-gax/build/src/normalCalls/retries.js:66:31)
    at Timeout._onTimeout (/home/ain-blockchain/node_modules/google-gax/build/src/normalCalls/retries.js:101:25)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:15736) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwin
g inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
 To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (se
e https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15736) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise reje
ctions that are not handled will terminate the Node.js process with a non-zero exit code.
express-rate-limit: req.ip is undefined - you can avoid this by providing a custom keyGenerator function, but it ma
y be indicative of a larger issue.
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xa1a640 node::Abort() [node]
 2: 0xa1aa4c node::OnFatalError(char const*, char const*) [node]
 3: 0xb9a62e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb9a9a9 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xd57c25  [node]
 6: 0xd582b6 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]
 7: 0xd64b75 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [nod
e]
 8: 0xd65a25 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReaso
n, v8::GCCallbackFlags) [node]
 9: 0xd684dc v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::Alloca
tionOrigin, v8::internal::AllocationAlignment) [node]
10: 0xd36a0d v8::internal::Factory::NewRawTwoByteString(int, v8::internal::AllocationType) [node]
11: 0x1105a39 v8::internal::IncrementalStringBuilder::Extend() [node]
12: 0xe4c77f v8::internal::JsonStringifier::SerializeString(v8::internal::Handle<v8::internal::String>) [node]
13: 0xe4de71 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Ha
ndle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
14: 0xe4f9d8 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Ha
ndle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
15: 0xe4f9d8 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Ha
ndle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
16: 0xe4f9d8 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Ha
ndle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
17: 0xe4f9d8 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Ha
ndle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
18: 0xe4f9d8 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Ha
ndle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
19: 0xe4f9d8 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Ha
ndle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
20: 0xe4f9d8 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Ha
ndle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
21: 0xe4f9d8 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Ha
ndle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
22: 0xe4f9d8 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Ha
ndle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
23: 0xe4f9d8 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Ha
ndle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
24: 0xe4f9d8 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Ha
ndle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
25: 0xe4f9d8 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Ha
ndle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
26: 0xe4f9d8 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Ha
ndle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
27: 0xe4f9d8 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Ha
ndle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
28: 0xe4f9d8 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Ha
ndle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
29: 0xe4f9d8 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Ha
ndle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
30: 0xe4f9d8 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Ha
ndle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
31: 0xe4f9d8 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Ha
ndle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
32: 0xe4f9d8 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Ha
ndle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
33: 0xe4f9d8 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Ha
ndle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
34: 0xe4f9d8 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Ha
ndle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
35: 0xe4f9d8 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Ha
ndle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
36: 0xe4f9d8 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Ha
ndle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
37: 0xe4f9d8 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Ha
ndle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
38: 0xe52386 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<false>(v8::internal::H
andle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
39: 0xe52d34 v8::internal::JsonStringify(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::in
ternal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [node]
40: 0xc4bdbb v8::internal::Builtin_JsonStringify(int, unsigned long*, v8::internal::Isolate*) [node]
41: 0x140dd19  [node]
```
@minsulee2 @liayoo

**Comment by platfowner** [comment]
![Screen Shot 2021-12-12 at 10 55 34 PM](https://user-images.githubusercontent.com/46211617/145715257-98efc14a-eef2-424b-8a4f-f953cf32b38d.jpg)

**Comment by platfowner** [comment]
https://nodejs.org/api/cli.html#--unhandled-rejectionsmode

**Comment by platfowner** [comment]
1. `--unhandled-rejections=throw`
2. add exception handling logic to logger

**Comment by platfowner** [comment]
Fixed, thanks!
