### ISSUE TITLE
[BUG] github ci/cd yarn install fails

### ISSUE THREAD

**Issue by platfowner** [ainblockchain/ain-blockchain#764]
It is recommended to use `--scripts-prepend-node-path` option.

<img width="1105" alt="Screen Shot 2021-12-08 at 4 55 20 PM" src="https://user-images.githubusercontent.com/46211617/145170183-563d90b4-dcb8-494c-9377-61143f7b9ae4.png">

error logs:
```
Run yarn install
yarn install v1.22.17
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
error /home/runner/work/ain-blockchain/ain-blockchain/node_modules/node-jq: Command failed.
Exit code: 1
Command: npm run install-binary
Arguments: 
Directory: /home/runner/work/ain-blockchain/ain-blockchain/node_modules/node-jq
Output:
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1638949612836-0.9379879862584162/node but npm is using /opt/hostedtoolcache/node/12.22.7/x64/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> node-jq@2.0.0 install-binary /home/runner/work/ain-blockchain/ain-blockchain/node_modules/node-jq
> node scripts/install-binary.js

Downloading jq from https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
GotError [HTTPError]: Response code 503 (Egress is over the account limit.)
    at EventEmitter.<anonymous> (/home/runner/work/ain-blockchain/ain-blockchain/node_modules/got/index.js:482:24)
    at EventEmitter.emit (events.js:314:20)
    at getResponse (/home/runner/work/ain-blockchain/ain-blockchain/node_modules/got/index.js:320:5)
    at Immediate.<anonymous> (/home/runner/work/ain-blockchain/ain-blockchain/node_modules/got/index.js:147:6)
    at processImmediate (internal/timers.js:461:21) {
  host: 'github.com',
  hostname: 'github.com',
  method: 'GET',
  path: '/stedolan/jq/releases/download/jq-1.6/jq-linux64',
  protocol: 'https:',
  url: 'https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64',
  statusCode: 503,
  statusMessage: 'Egress is over the account limit.',
  headers: {
    connection: 'close',
    'content-length': '212',
    'content-type': 'application/xml',
    server: 'Microsoft-HTTPAPI/2.0',
    'x-ms-request-id': '41719ffe-e01e-002c-7b07-ecceca000000',
    'x-ms-error-code': 'ServerBusy',
    'fastly-restarts': '1',
    'accept-ranges': 'bytes',
    date: 'Wed, 08 Dec 2021 07:46:59 GMT',
    via: '1.1 varnish',
    'x-served-by': 'cache-bwi5067-BWI',
    'x-cache': 'MISS',
    'x-cache-hits': '0',
    'x-timer': 'S1638949614.068356,VS0,VE5022'
  }
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-jq@2.0.0 install-binary: `node scripts/install-binary.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-jq@2.0.0 install-binary script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-12-08T07_46_59_106Z-debug.log
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Process completed with exit code 1.
```

**Comment by platfowner** [comment]
Not reproducible.
