### ISSUE TITLE
[BUG] RangeError: Invalid string length

### ISSUE THREAD

**Issue by cshcomcom** [ainblockchain/ain-blockchain#846]
**To Reproduce**
1. I try to write 5GB value to test the memory limit.
2. I see this error
```
{"name":"testnet-dev","hostname":"dev-node-0-taiwan","pid":14247,"level":50,"msg":"[NODE] [loadAndExecuteChainOnDb] Failed to validate and execute block 0: RangeError: Invalid string length\n    at JSON.stringify (<anonymous>)\n    at Function.writeSnapshot (/home/ain-blockchain/common/file-util.js:226:65)\n    at BlockchainNode.updateSnapshots (/home/ain-blockchain/node/index.js:350:16)\n    at BlockchainNode.cloneAndFinalizeVersion (/home/ain-blockchain/node/index.js:344:10)\n    at BlockchainNode.loadAndExecuteChainOnDb (/home/ain-blockchain/node/index.js:679:18)\n    at BlockchainNode.initNode (/home/ain-blockchain/node/index.js:268:17)\n    at P2pClient.startBlockchainNode (/home/ain-blockchain/p2p/index.js:342:29)\n    at P2pClient.run (/home/ain-blockchain/p2p/index.js:46:20)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\nError\n    at Function.logErrorWithStackTrace (/home/ain-blockchain/common/common-util.js:785:33)\n    at Function.finishWithStackTrace (/home/ain-blockchain/common/common-util.js:795:16)\n    at BlockchainNode.loadAndExecuteChainOnDb (/home/ain-blockchain/node/index.js:685:20)\n    at BlockchainNode.initNode (/home/ain-blockchain/node/index.js:268:17)\n    at P2pClient.startBlockchainNode (/home/ain-blockchain/p2p/index.js:342:29)\n    at P2pClient.run (/home/ain-blockchain/p2p/index.js:46:20)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5).","time":"2021-12-29T12:43:32.977Z","v":0}
```

I think this error comes from `JSON.stringify` in `writeSnapshot`, because string type data cannot exceed 2 gigabytes. ([ref](https://stackoverflow.com/questions/24153996/is-there-a-limit-on-the-size-of-a-string-in-json-with-node-js?lq=1))

**Comment by cshcomcom** [comment]
It seems to be two ways. Split the snapshot and save it or use a stream?

**Comment by liayoo** [comment]
Should we try something like this? https://github.com/Faleij/json-stream-stringify
cc: @platfowner @minsulee2

**Comment by liayoo** [comment]
> Should we try something like this? https://github.com/Faleij/json-stream-stringify cc: @platfowner @minsulee2

Testing on branch feature/liayoo/write-stream

**Comment by platfowner** [comment]
Fixed, thanks!
