### ISSUE TITLE
[BUG] Failed to load block 0 with --no-keep-data

### ISSUE THREAD

**Issue by platfowner** [ainblockchain/ain-blockchain#894]
commands:
```
bash deploy_blockchain_genesis_gcp.sh dev <Username> 0 --no-keep-code --no-keep-data
```

logs:
```
  1 {"name":"testnet-dev","hostname":"dev-node-0-taiwan","pid":15086,"level":50,"msg":"[NODE] [loadAndExecuteChainO
    nDb] Failed to load block 0.\nError\n    at Function.logErrorWithStackTrace (/home/ain-blockchain-2022-01-08T18
    -25/common/common-util.js:799:33)\n    at Function.finishWithStackTrace (/home/ain-blockchain-2022-01-08T18-25/
    common/common-util.js:809:16)\n    at BlockchainNode.loadAndExecuteChainOnDb (/home/ain-blockchain-2022-01-08T1
    8-25/node/index.js:687:20)\n    at BlockchainNode.initNode (/home/ain-blockchain-2022-01-08T18-25/node/index.js
    :267:17)\n    at P2pClient.startBlockchainNode (/home/ain-blockchain-2022-01-08T18-25/p2p/index.js:384:36)\n   
     at P2pClient.run (/home/ain-blockchain-2022-01-08T18-25/p2p/index.js:50:20)\n    at processTicksAndRejections 
    (node:internal/process/task_queues:96:5).","time":"2022-01-08T18:25:41.833Z","v":0}
```

**Comment by platfowner** [comment]
Fixed, thanks!
