### ISSUE TITLE
Failed to add new block, TypeError: Cannot read properties of undefined (reading 'timestamp')

### ISSUE THREAD

**Issue by liayoo** [ainblockchain/ain-blockchain#906]
While test deploying to dev with a command `bash deploy_blockchain_incremental_gcp.sh dev lia 0 0 0 --keystore --no-keep-data --no-keep-code`, the following error was observed:

[NODE] [mergeChainSegment] Failed to add new block (1 / 0xda250c82aaa8266f6230c8b27249f3b5554dc31d34996b5c5d371b9699f1410e) to chain: TypeError: Cannot read properties of undefined (reading 'timestamp')
    at BlockchainNode.buildBlockchainSnapshot (/home/ain-blockchain-2022-01-11T05-42/node/index.js:373:34)
    at Function.validateStateProofHash (/home/ain-blockchain-2022-01-11T05-42/consensus/index.js:757:31)
    at Function.validateAndExecuteBlockOnDb (/home/ain-blockchain-2022-01-11T05-42/consensus/index.js:848:17)
    at BlockchainNode.mergeChainSegment (/home/ain-blockchain-2022-01-11T05-42/node/index.js:755:19)
    at P2pClient.handleChainSegment (/home/ain-blockchain-2022-01-11T05-42/p2p/index.js:690:42)
    at WebSocket.<anonymous> (/home/ain-blockchain-2022-01-11T05-42/p2p/index.js:626:16)
    at WebSocket.emit (node:events:390:28)
    at Receiver.receiverOnMessage (/home/ain-blockchain-2022-01-11T05-42/node_modules/ws/lib/websocket.js:1008:20)
    at Receiver.emit (node:events:390:28)
    at Receiver.dataMessage (/home/ain-blockchain-2022-01-11T05-42/node_modules/ws/lib/receiver.js:517:14)

**Comment by platfowner** [comment]
Fixed, thanks!
