### ISSUE TITLE
[BUG] 2 nodes (0, 5) not working (mainnet, spring)

### ISSUE THREAD

**Issue by platfowner** [ainblockchain/ain-blockchain#948]
![num_nodex_alive](https://user-images.githubusercontent.com/46211617/153718179-6003a093-af6f-43cf-b22e-94488817500c.jpg)

![block_number](https://user-images.githubusercontent.com/46211617/153718180-400be80c-0ba4-45ab-8b2f-9db2148c4b50.jpg)

```
$ ls -la error_logs.txt 
-rw-rw-r-- 1 seo seo 9711836909 Feb 12 15:35 error_logs.txt
```

```
$ head -n 100 error_logs.txt 
express-rate-limit: req.ip is undefined - you can avoid this by providing a custom keyGenerator function, but it ma
y be indicative of a larger issue.
express-rate-limit: req.ip is undefined - you can avoid this by providing a custom keyGenerator function, but it ma
y be indicative of a larger issue.
express-rate-limit: req.ip is undefined - you can avoid this by providing a custom keyGenerator function, but it ma
y be indicative of a larger issue.
express-rate-limit: req.ip is undefined - you can avoid this by providing a custom keyGenerator function, but it ma
y be indicative of a larger issue.
TypeError: Cannot read properties of undefined (reading 'replace')
    at convertIpv6ToIpv4 (/home/ain-blockchain-2022-02-09T08-11/common/network-util.js:123:18)
    at /home/ain-blockchain-2022-02-09T08-11/client/index.js:118:16
    at middleware (/home/ain-blockchain-2022-02-09T08-11/node_modules/ip-whitelist/index.js:22:25)
    at Layer.handle [as handle_request] (/home/ain-blockchain-2022-02-09T08-11/node_modules/express/lib/router/laye
r.js:95:5)
    at trim_prefix (/home/ain-blockchain-2022-02-09T08-11/node_modules/express/lib/router/index.js:323:13)
    at /home/ain-blockchain-2022-02-09T08-11/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/ain-blockchain-2022-02-09T08-11/node_modules/express/lib/router/index.js:341:
12)
    at next (/home/ain-blockchain-2022-02-09T08-11/node_modules/express/lib/router/index.js:275:10)
    at /home/ain-blockchain-2022-02-09T08-11/node_modules/express-rate-limit/lib/express-rate-limit.js:170:15
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
ERROR: Simultaneous requests running!
ERROR: Simultaneous requests running!
ERROR: Simultaneous requests running!
ERROR: Simultaneous requests running!
ERROR: Simultaneous requests running!
ERROR: Simultaneous requests running!
ERROR: Simultaneous requests running!
ERROR: Simultaneous requests running!
ERROR: Simultaneous requests running!
ERROR: Simultaneous requests running!
ERROR: Simultaneous requests running!
ERROR: Simultaneous requests running!
...
```

```
$ tail -n 100 error_logs.txt 
RangeError: Invalid array length
ERROR: Simultaneous requests running!
Exception in PromiseRejectCallback:
node:internal/process/promises:150
  ArrayPrototypePush(pendingUnhandledRejections, promise);
  ^
RangeError: Invalid array length
ERROR: Simultaneous requests running!
Exception in PromiseRejectCallback:
node:internal/process/promises:150
  ArrayPrototypePush(pendingUnhandledRejections, promise);
  ^
RangeError: Invalid array length
ERROR: Simultaneous requests running!
Exception in PromiseRejectCallback:
node:internal/process/promises:150
  ArrayPrototypePush(pendingUnhandledRejections, promise);
  ^
RangeError: Invalid array length
ERROR: Simultaneous requests running!
Exception in PromiseRejectCallback:
node:internal/process/promises:150
  ArrayPrototypePush(pendingUnhandledRejections, promise);
  ^
RangeError: Invalid array length
ERROR: Simultaneous requests running!
Exception in PromiseRejectCallback:
node:internal/process/promises:150
  ArrayPrototypePush(pendingUnhandledRejections, promise);
  ^
```

**Comment by platfowner** [comment]
Let me restart node 0 and node 5 jobs. @liayoo @minsulee2

**Comment by platfowner** [comment]
![num_nodes_alive_for_0](https://user-images.githubusercontent.com/46211617/153718716-d38d1684-eb1a-4bc7-8cb2-199973430c9b.jpg)


![consensus_status_health_for_node_0](https://user-images.githubusercontent.com/46211617/153718723-f6faa46e-1db7-4916-991d-5e76662c0e7f.jpg)

**Comment by platfowner** [comment]
node 5 restarted successfully:
```
bash deploy_blockchain_incremental_gcp.sh mainnet <username> 0 5 5 --keystore
```

**Comment by platfowner** [comment]
![num_nodes_alive_for_node_5](https://user-images.githubusercontent.com/46211617/153719202-af20ae3f-2a87-4de4-acc6-cc87770aeff5.jpg)

![consensus_status_health_for_node_5](https://user-images.githubusercontent.com/46211617/153719205-0986846c-2f97-43d5-9189-c280b202f5cd.jpg)

![block_number_for_node_5](https://user-images.githubusercontent.com/46211617/153719208-a3d677b4-0aa4-429b-8a8a-5668260ac438.jpg)

**Comment by platfowner** [comment]
(spring) node 0 restarted successfully:
```
bash deploy_blockchain_incremental_gcp.sh spring <username> 0 0 0 --keystore
```

(spring) node 5 restarted successfully:
```
bash deploy_blockchain_incremental_gcp.sh spring <username> 0 5 5 --keystore
```

![num_nodes_alive](https://user-images.githubusercontent.com/46211617/153721342-0c504035-e46e-4f1b-b4e9-902569fa54e1.jpg)

**Comment by platfowner** [comment]
spin-off'ed issue: https://github.com/ainblockchain/ain-blockchain/issues/971

**Comment by platfowner** [comment]
Now let me close this issue.
