### ISSUE TITLE
[BUG] (convertIpv6ToIpv4) TypeError: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by platfowner** [ainblockchain/ain-blockchain#971]
error_logs.txt:
```
express-rate-limit: req.ip is undefined - you can avoid this by providing a custom keyGenerator function, but it may
 be indicative of a larger issue.
express-rate-limit: req.ip is undefined - you can avoid this by providing a custom keyGenerator function, but it may
 be indicative of a larger issue.
express-rate-limit: req.ip is undefined - you can avoid this by providing a custom keyGenerator function, but it may
 be indicative of a larger issue.
express-rate-limit: req.ip is undefined - you can avoid this by providing a custom keyGenerator function, but it may
 be indicative of a larger issue.
express-rate-limit: req.ip is undefined - you can avoid this by providing a custom keyGenerator function, but it may
 be indicative of a larger issue.
express-rate-limit: req.ip is undefined - you can avoid this by providing a custom keyGenerator function, but it may
 be indicative of a larger issue.
express-rate-limit: req.ip is undefined - you can avoid this by providing a custom keyGenerator function, but it may
 be indicative of a larger issue.
TypeError: Cannot read properties of undefined (reading 'replace')
    at convertIpv6ToIpv4 (/home/ain-blockchain-2022-02-09T08-11/common/network-util.js:123:18)
    at /home/ain-blockchain-2022-02-09T08-11/client/index.js:118:16
    at middleware (/home/ain-blockchain-2022-02-09T08-11/node_modules/ip-whitelist/index.js:22:25)
    at Layer.handle [as handle_request] (/home/ain-blockchain-2022-02-09T08-11/node_modules/express/lib/router/layer
.js:95:5)
    at trim_prefix (/home/ain-blockchain-2022-02-09T08-11/node_modules/express/lib/router/index.js:323:13)
    at /home/ain-blockchain-2022-02-09T08-11/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/ain-blockchain-2022-02-09T08-11/node_modules/express/lib/router/index.js:341:1
2)
    at next (/home/ain-blockchain-2022-02-09T08-11/node_modules/express/lib/router/index.js:275:10)
    at /home/ain-blockchain-2022-02-09T08-11/node_modules/express-rate-limit/lib/express-rate-limit.js:170:15
    at runMicrotasks (<anonymous>)
express-rate-limit: req.ip is undefined - you can avoid this by providing a custom keyGenerator function, but it may
 be indicative of a larger issue.
```

**Comment by platfowner** [comment]
Some messages are still observed:
error_logs.txt:
```
express-rate-limit: req.ip is undefined - you can avoid this by providing a custom keyGenerator function, but it may be indicative of a larger issue.
express-rate-limit: req.ip is undefined - you can avoid this by providing a custom keyGenerator function, but it may be indicative of a larger issue.
express-rate-limit: req.ip is undefined - you can avoid this by providing a custom keyGenerator function, but it may be indicative of a larger issue.
express-rate-limit: req.ip is undefined - you can avoid this by providing a custom keyGenerator function, but it may be indicative of a larger issue.
express-rate-limit: req.ip is undefined - you can avoid this by providing a custom keyGenerator function, but it may be indicative of a larger issue.
express-rate-limit: req.ip is undefined - you can avoid this by providing a custom keyGenerator function, but it may be indicative of a larger issue.
```
